!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of compf in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *tsal *pres compf
!   with respect to varying inputs: *temp *tsal *pres
!   Plus diff mem management of: temp:in tsal:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief compf(i,j,k,ismpl) calculates the compressibility of the fluid
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return compf  [1 / Pa]
!> @details
!> compf(i,j,k,ismpl) calculates the compressibility in (in 1/Pa) of
!> salin water, given temperature (t, in c) pressure (p,in pa), and
!> salinity (s, in mol/L) at node(i,j,k)\n\n
!>
!> Sources:\n
!> Driesner & Heinrich, The system H2O-NaCl. Part I: Correlation
!>    formulae for phase relations in temperature-pressure-composition
!>    space from 0 to 1000 C, 0 to 5000 bar, and 0 to 1 XNaCl
!>    Geochimica et Cosmochimica Acta 71 (2007) 4880-4901\n\n
!>
!> Driesner, The system H2O-NaCl. Part II: Correlations for molar
!>    volume, enthalpy, and isobaric heat capacity from 0 to 1000 C, 1
!>    to 5000 bar, and 0 to 1 XNaCl Geochimica et Cosmochimica Acta 71
!>    (2007) 4902-4919\n\n
SUBROUTINE COMPF_AD(i, j, k, ismpl, compf_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_FLOW
  IMPLICIT NONE
  double precision :: compf_adv
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Molar mass of NaCl [g/mol]
  DOUBLE PRECISION, PARAMETER :: mmnacl=58.44277d0
! Mass fraction of NaCl in solution [-]
  DOUBLE PRECISION :: fracnacl
  DOUBLE PRECISION :: fracnacl_ad
! Molar mass of water, H2O [g/mol]
  DOUBLE PRECISION, PARAMETER :: mmwater=18.01528d0
! Temperature, [degC]
  DOUBLE PRECISION :: t
  DOUBLE PRECISION :: t_ad
! Pressure [MPa]
  DOUBLE PRECISION :: p
  DOUBLE PRECISION :: p_ad
! Monomials of pressure [bar]
  DOUBLE PRECISION :: pb, pb2, pb3
  DOUBLE PRECISION :: pb_ad, pb2_ad, pb3_ad
! Pure water compressibility [1/Pa]
  DOUBLE PRECISION :: cw
  DOUBLE PRECISION :: cw_ad
  DOUBLE PRECISION, EXTERNAL :: COMPW
! Pure water density [kg/m3]
  DOUBLE PRECISION :: rw
  DOUBLE PRECISION :: rw_ad
  DOUBLE PRECISION, EXTERNAL :: RHOW
! Local salinity [mol/kg]
  DOUBLE PRECISION :: s
  DOUBLE PRECISION :: s_ad
! Mole fraction of NaCl [-]
  DOUBLE PRECISION :: xnacl
  DOUBLE PRECISION :: xnacl_ad
! Temperature at which pure water has the same molar volume
! as the solution [K]
  DOUBLE PRECISION :: tv
  DOUBLE PRECISION :: tv_ad
! Driesner2007: Coefficients
! Equation (9)
  DOUBLE PRECISION :: n1, n10, n11, n12
  DOUBLE PRECISION :: n1_ad, n10_ad, n11_ad, n12_ad
! Equation (10)
  DOUBLE PRECISION :: n2, n20, n21, n22, n23
  DOUBLE PRECISION :: n2_ad, n20_ad, n21_ad, n22_ad, n23_ad
! Equation (11), (12)
  DOUBLE PRECISION :: n1x, n2x
  DOUBLE PRECISION :: n1x_ad, n2x_ad
! Table 4
  DOUBLE PRECISION :: n30, n300, n301, n302
  DOUBLE PRECISION :: n30_ad, n300_ad, n301_ad, n302_ad
  DOUBLE PRECISION :: n31, n310, n311, n312
  DOUBLE PRECISION :: n31_ad, n310_ad, n311_ad, n312_ad
! Deviation function (13)
  DOUBLE PRECISION :: dt
  DOUBLE PRECISION :: dt_ad
  INTRINSIC EXP
  INTRINSIC SQRT
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: temporary_ad0
  DOUBLE PRECISION :: compf
! Local temperature [degC]
  t = temp(i, j, k, ismpl)
! Local pressure [MPa]
  p = pres(i, j, k, ismpl)*pa_conv1
! Local salinity [mol/L]
  s = tsal(i, j, k, ismpl)
! pure water compressibility [1 / Pa]
  IF (s .LE. 0.0d0) THEN
    cw_ad = compf_adv
    p_ad = 0.D0
    s_ad = 0.D0
    t_ad = 0.D0
  ELSE
! pure water density [g/L = kg/m3]
    rw = RHOW(p, t)
! Pressure [bar] and pressure monomials
    pb = p*10.0d0
    pb2 = pb*pb
    pb3 = pb*pb2
! Mass fraction of NaCl, mol/L > (g/L) / (g/L) mass fraction
    fracnacl = s*mmnacl/(rw+s*mmnacl)
! Mole fraction of NaCl, (mol/L) / (mol/L)
    xnacl = fracnacl/mmnacl/(fracnacl/mmnacl+(1-fracnacl)/mmwater)
! Driesner2007 parameters, Table 4
    n11 = -54.2958d0 - 45.7623d0*EXP(-(9.44785d-4*pb))
    n21 = -2.6142d0 - 0.000239092d0*pb
    n22 = 0.0356828d0 + 4.37235d-6*pb + 2.0566d-9*pb2
    n300 = 7.60664d6/(pb+472.051d0)**2
    n301 = -50.0d0 - 86.1446d0*EXP(-(6.21128d-4*pb))
    n302 = 294.318d0*EXP(-(5.66735d-3*pb))
    n310 = -(0.0732761d0*EXP(-(2.3772d-3*pb))) - 5.2948d-5*pb
    n311 = -47.2747d0 + 24.3653d0*EXP(-(1.25533d-3*pb))
    n312 = -0.278529 - 0.00081381*pb
! Driesner2007: n1 and n2 parameters for liquid NaCl
    n1x = 330.47d0 + 0.942876d0*SQRT(pb) + 0.0817193*pb - 2.47556d-8*pb2&
&     + 3.45052d-10*pb3
    n2x = -0.0370751 + 0.00237723*SQRT(pb) + 5.42049d-5*pb + 5.84709d-9*&
&     pb2 - 5.99373d-13*pb3
! Driesner2007: Set xnacl=1 in (9), => n1 = n1x
    n10 = n1x
! Driesner2007: Set xnacl=0 in (9) => n1 = 0.0d0
    n12 = -n10 - n11
! Driesner2007: Set xnacl=0 in (10) => n2 = 1.0d0
    n20 = 1.0d0 - n21*SQRT(n22)
! Driesner2007: Set xnacl=1 in (10) => n2 = n2x
    n23 = n2x - n20 - n21*SQRT(1.0d0+n22)
! Driesner2007: Equation (9)
    n1 = n10 + n11*(1.0d0-xnacl) + n12*(1.0d0-xnacl)**2
! Driesner2007: Equation (10)
    n2 = n20 + n21*SQRT(xnacl+n22) + n23*xnacl
! Driesner2007: deviation function D(T) Equations (14)-(16)
    n30 = n300*(EXP(n301*xnacl)-1.0d0) + n302*xnacl
    n31 = n310*EXP(n311*xnacl) + n312*xnacl
    dt = n30*EXP(n31*t)
! Temperature at which pure water has the same molar volume
! as the solution
    tv = n1 + n2*t + dt
! Pure water compressibility at tv
    p_ad = 0.D0
    tv_ad = 0.D0
    CALL COMPW_AD0(p, p_ad, tv, tv_ad, compf_adv)
    n1_ad = tv_ad
    n2_ad = t*tv_ad
    dt_ad = tv_ad
    n30_ad = EXP(n31*t)*dt_ad
    temporary_ad0 = EXP(n31*t)*n30*dt_ad
    t_ad = n2*tv_ad + n31*temporary_ad0
    n31_ad = t*temporary_ad0
    n310_ad = EXP(n311*xnacl)*n31_ad
    temporary_ad0 = EXP(n311*xnacl)*n310*n31_ad
    n312_ad = xnacl*n31_ad
    xnacl_ad = n312*n31_ad + n311*temporary_ad0
    n311_ad = xnacl*temporary_ad0
    n300_ad = (EXP(n301*xnacl)-1.0d0)*n30_ad
    temporary_ad0 = EXP(n301*xnacl)*n300*n30_ad
    n302_ad = xnacl*n30_ad
    n301_ad = xnacl*temporary_ad0
    temp0 = SQRT(xnacl + n22)
    n21_ad = temp0*n2_ad
    IF (xnacl + n22 .EQ. 0.0) THEN
      temporary_ad = 0.D0
    ELSE
      temporary_ad = n21*n2_ad/(2.0*temp0)
    END IF
    xnacl_ad = xnacl_ad + n302*n30_ad + n301*temporary_ad0 + n23*n2_ad + &
&     temporary_ad - (n11+2*(1.0d0-xnacl)*n12)*n1_ad
    n23_ad = xnacl*n2_ad
    n20_ad = n2_ad - n23_ad
    n12_ad = (1.0d0-xnacl)**2*n1_ad
    n10_ad = n1_ad - n12_ad
    n11_ad = (1.0d0-xnacl)*n1_ad - n12_ad
    temp0 = SQRT(n22 + 1.0d0)
    IF (n22 + 1.0d0 .EQ. 0.0) THEN
      n22_ad = temporary_ad
    ELSE
      n22_ad = temporary_ad - n21*n23_ad/(2.0*temp0)
    END IF
    n2x_ad = n23_ad
    n21_ad = n21_ad - temp0*n23_ad
    temp0 = SQRT(n22)
    n21_ad = n21_ad - temp0*n20_ad
    IF (.NOT.n22 .EQ. 0.0) n22_ad = n22_ad - n21*n20_ad/(2.0*temp0)
    n1x_ad = n10_ad
    IF (pb .EQ. 0.0) THEN
      pb_ad = 0.D0
    ELSE
      pb_ad = 0.00237723*n2x_ad/(2.0*SQRT(pb))
    END IF
    pb3_ad = 3.45052d-10*n1x_ad - 5.99373d-13*n2x_ad
    pb2_ad = 5.84709d-9*n2x_ad + 2.0566d-9*n22_ad - 2.47556d-8*n1x_ad + &
&     pb*pb3_ad
    IF (pb .EQ. 0.0) THEN
      pb_ad = pb_ad + 5.42049d-5*n2x_ad + 0.0817193*n1x_ad + (2.3772d-3*&
&       EXP(-(2.3772d-3*pb))*0.0732761d0-5.2948d-5)*n310_ad - 0.00081381&
&       *n312_ad - 1.25533d-3*EXP(-(1.25533d-3*pb))*24.3653d0*n311_ad + &
&       6.21128d-4*EXP(-(6.21128d-4*pb))*86.1446d0*n301_ad - 5.66735d-3*&
&       EXP(-(5.66735d-3*pb))*294.318d0*n302_ad + 4.37235d-6*n22_ad - 2*&
&       7.60664d6*n300_ad/(pb+472.051d0)**3 + 9.44785d-4*EXP(-(&
&       9.44785d-4*pb))*45.7623d0*n11_ad - 0.000239092d0*n21_ad + pb2*&
&       pb3_ad + 2*pb*pb2_ad
    ELSE
      pb_ad = pb_ad + 5.42049d-5*n2x_ad + (0.942876d0/(2.0*SQRT(pb))+&
&       0.0817193)*n1x_ad + (2.3772d-3*EXP(-(2.3772d-3*pb))*0.0732761d0-&
&       5.2948d-5)*n310_ad - 0.00081381*n312_ad - 1.25533d-3*EXP(-(&
&       1.25533d-3*pb))*24.3653d0*n311_ad + 6.21128d-4*EXP(-(6.21128d-4*&
&       pb))*86.1446d0*n301_ad - 5.66735d-3*EXP(-(5.66735d-3*pb))*&
&       294.318d0*n302_ad + 4.37235d-6*n22_ad - 2*7.60664d6*n300_ad/(pb+&
&       472.051d0)**3 + 9.44785d-4*EXP(-(9.44785d-4*pb))*45.7623d0*&
&       n11_ad - 0.000239092d0*n21_ad + pb2*pb3_ad + 2*pb*pb2_ad
    END IF
    temp0 = mmnacl*(fracnacl/mmnacl+(-fracnacl+1)/mmwater)
    temporary_ad = -(mmnacl*fracnacl*xnacl_ad/temp0**2)
    fracnacl_ad = xnacl_ad/temp0 + (1.0/mmnacl-1.0/mmwater)*temporary_ad
    temporary_ad = mmnacl*fracnacl_ad/(rw+mmnacl*s)
    temporary_ad0 = -(s*temporary_ad/(rw+mmnacl*s))
    s_ad = temporary_ad + mmnacl*temporary_ad0
    rw_ad = temporary_ad0
    p_ad = p_ad + 10.0d0*pb_ad
    CALL RHOW_AD0(p, p_ad, t, t_ad, rw_ad)
    cw_ad = 0.D0
  END IF
  CALL COMPW_AD0(p, p_ad, t, t_ad, cw_ad)
  tsal_ad(i, j, k, ismpl) = tsal_ad(i, j, k, ismpl) + s_ad
  pres_ad(i, j, k, ismpl) = pres_ad(i, j, k, ismpl) + pa_conv1*p_ad
  temp_ad(i, j, k, ismpl) = temp_ad(i, j, k, ismpl) + t_ad
END SUBROUTINE COMPF_AD

