!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of compw in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: compw t_h p_h
!   with respect to varying inputs: t_h p_h
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief compw calculates compressibility of pure water
!> @param[in] p_h pressure [MPa]
!> @param[in] t_h temperature [degC]
!> @return  compressibility                     compw  [1./Pa]
!> @details
!> compw calculates compressibility of pure water [1/Pa]
!> given temperature (t, in C), and pressure (p,in MPa)
!> at pressure/temperature (p_h,t).\n \n
!>
!> Method: \n
!>
!> compw = 1/rhow d/dP rhow, \n
!>
!> where rhow= water density.\n \n
!>
!>  Main source Zyvoloski1997: \n
!>
!> Zyvoloski, G.A., Robinson, B.A., Dash, Z.V., & Trease, L.L. Summary
!> of the models and methods for the FEHM application - a
!> finite-element heat- and mass-transfer code. United
!> States. doi:10.2172/565545. \n \n
!>
!> See Section 8.4.3. of Zyvoloski1997 for an explanation of the
!> "Rational function approximation" used in this subroutine. \n \n
!> The approximation uses the table of coefficients in Appendix 10 of
!> Zyvoloski1997.\n
!>
!> Alternative source (same text, more modern, without doi): \n
!> https://fehm.lanl.gov/orgs/ees/fehm/pdfs/fehm_mms.pdf \n \n
!>
!> The table of coefficients from Zyvoloski1997 describes the physical
!> values found in Haar1984: \n
!>
!> Lester Haar, John Gallagher, George Kell, NBS/NRC Steam Tables:
!> Thermodynamic and Transport Properties and Computer Programs for
!> Vapor and Liquid States of Water in SI Units, Hemisphere Publishing
!> Corporation, Washington, 1984. \n \n
!>
!>    range of validity:\n
!>    - pressures   0.001 - 110 MPa,\n
!>    - temperature   15 - 360 degC\n \n
!>
!> input:\n
!>   pressure                               p [MPa]\n
!>   temperature                         t in [degC]\n
SUBROUTINE COMPW_AD0(p_h, p_h_ad, t_h, t_h_ad, compw_ad)
  USE MOD_FLOW
  IMPLICIT NONE
! Input Pressure (MPa)
  DOUBLE PRECISION :: p_h
  DOUBLE PRECISION :: p_h_ad
! Input temperature (degc)
  DOUBLE PRECISION :: t_h
  DOUBLE PRECISION :: t_h_ad
! Monomials of temperature and pressure
  DOUBLE PRECISION :: t, t2, t3
  DOUBLE PRECISION :: t_ad, t2_ad, t3_ad
  DOUBLE PRECISION :: p, p2, p3, p4
  DOUBLE PRECISION :: p_ad, p2_ad, p3_ad
  DOUBLE PRECISION :: tp, t2p, tp2
  DOUBLE PRECISION :: tp_ad, t2p_ad, tp2_ad
! Coefficients of numerator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: y0=0.10000000d+01
  DOUBLE PRECISION, PARAMETER :: y1=0.17472599d-01
  DOUBLE PRECISION, PARAMETER :: y2=-0.20443098d-04
  DOUBLE PRECISION, PARAMETER :: y3=-0.17442012d-06
  DOUBLE PRECISION, PARAMETER :: y4=0.49564109d-02
  DOUBLE PRECISION, PARAMETER :: y5=-0.40757664d-04
  DOUBLE PRECISION, PARAMETER :: y6=0.50676664d-07
  DOUBLE PRECISION, PARAMETER :: y7=0.50330978d-04
  DOUBLE PRECISION, PARAMETER :: y8=0.33914814d-06
  DOUBLE PRECISION, PARAMETER :: y9=-0.18383009d-06
! Coefficients of denominator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: z0=0.10009476d-02
  DOUBLE PRECISION, PARAMETER :: z1=0.16812589d-04
  DOUBLE PRECISION, PARAMETER :: z2=-0.24582622d-07
  DOUBLE PRECISION, PARAMETER :: z3=-0.17014984d-09
  DOUBLE PRECISION, PARAMETER :: z4=0.48841156d-05
  DOUBLE PRECISION, PARAMETER :: z5=-0.32967985d-07
  DOUBLE PRECISION, PARAMETER :: z6=0.28619380d-10
  DOUBLE PRECISION, PARAMETER :: z7=0.53249055d-07
  DOUBLE PRECISION, PARAMETER :: z8=0.30456698d-09
  DOUBLE PRECISION, PARAMETER :: z9=-0.12221899d-09
! Numerator and denominator of rational function approximation
  DOUBLE PRECISION :: ta, tb
  DOUBLE PRECISION :: ta_ad, tb_ad
! Derivative of numerator wrt P
  DOUBLE PRECISION :: da
  DOUBLE PRECISION :: da_ad
! Derivative of denominator wrt P
  DOUBLE PRECISION :: db
  DOUBLE PRECISION :: db_ad
! Denominator squared
  DOUBLE PRECISION :: b2
  DOUBLE PRECISION :: b2_ad
! Water density (local)
  DOUBLE PRECISION :: rhow_loc
  DOUBLE PRECISION :: rhow_loc_ad
! Derivative of water density wrt P
  DOUBLE PRECISION :: drhodp
  DOUBLE PRECISION :: drhodp_ad
! Compressibiliy in Mpa
  DOUBLE PRECISION :: compw_mpa
  DOUBLE PRECISION :: compw_mpa_ad
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: compw
  DOUBLE PRECISION :: compw_ad
! pressure [MPa]
  p = p_h
! temperature [degC]
  t = t_h
! Compute monomials in pressure and temperature
  p2 = p*p
  p3 = p2*p
  t2 = t*t
  t3 = t2*t
  tp = p*t
  t2p = t2*p
  tp2 = t*p2
! Numerator of rational function approximation
  ta = y0 + y1*p + y2*p2 + y3*p3 + y4*t + y5*t2 + y6*t3 + y7*tp + y8*tp2&
&   + y9*t2p
! Denominator of rational function approximation
  tb = z0 + z1*p + z2*p2 + z3*p3 + z4*t + z5*t2 + z6*t3 + z7*tp + z8*tp2&
&   + z9*t2p
! Water density
  rhow_loc = ta/tb
! Derivative of numerator
  da = y1 + 2.d0*y2*p + 3.d0*y3*p2 + y7*t + 2.d0*y8*tp + y9*t2
! Derivative of denominator
  db = z1 + 2.d0*z2*p + 3.d0*z3*p2 + z7*t + 2.0*z8*tp + z9*t2
! Denominator squared
  b2 = tb*tb
! Derivative, quotient rule
  drhodp = (da*tb-ta*db)/b2
! Compressibility: (1/rhow_loc) * drhodp [1/MPa]
! Compressibility [1/Pa]
  compw_mpa_ad = compw_ad/pa_conv
  drhodp_ad = compw_mpa_ad/rhow_loc
  rhow_loc_ad = -(drhodp*compw_mpa_ad/rhow_loc**2)
  temporary_ad = drhodp_ad/b2
  da_ad = tb*temporary_ad
  ta_ad = rhow_loc_ad/tb - db*temporary_ad
  db_ad = -(ta*temporary_ad)
  b2_ad = -((da*tb-ta*db)*temporary_ad/b2)
  tb_ad = da*temporary_ad + 2*tb*b2_ad - ta*rhow_loc_ad/tb**2
  tp_ad = z8*2.0*db_ad + y8*2.d0*da_ad + z7*tb_ad + y7*ta_ad
  p3_ad = z3*tb_ad + y3*ta_ad
  t3_ad = z6*tb_ad + y6*ta_ad
  tp2_ad = z8*tb_ad + y8*ta_ad
  p2_ad = z3*3.d0*db_ad + y3*3.d0*da_ad + z2*tb_ad + y2*ta_ad + t*tp2_ad&
&   + p*p3_ad
  t2p_ad = z9*tb_ad + y9*ta_ad
  p_ad = z2*2.d0*db_ad + y2*2.d0*da_ad + z1*tb_ad + y1*ta_ad + t2*t2p_ad&
&   + t*tp_ad + p2*p3_ad + 2*p*p2_ad
  t2_ad = z9*db_ad + y9*da_ad + z5*tb_ad + y5*ta_ad + p*t2p_ad + t*t3_ad
  t_ad = z7*db_ad + y7*da_ad + z4*tb_ad + y4*ta_ad + p2*tp2_ad + p*tp_ad&
&   + t2*t3_ad + 2*t*t2_ad
  t_h_ad = t_h_ad + t_ad
  p_h_ad = p_h_ad + p_ad
END SUBROUTINE COMPW_AD0

