!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of rhof in forward (tangent) mode:
!   variations   of useful results: rhof
!   with respect to varying inputs: *temp *tsal *pres
!   Plus diff mem management of: temp:in tsal:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief rhof(i,j,k,ismpl) calculates the density of the fluid (in kg/m^3),
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return rho  [kg/m^3]
!> @details
!> rhow(i,j,k,ismpl) calculates the density in (in kg/m^3) of brine,
!> given temperature (t, in c) pressure (p,in pa), and salinity (s, in
!> mol/L) at node(i,j,k)\n
!>
!> Source:\n
!> Batzle, M., & Wang, Z., Seismic properties of pore fluids,
!> GEOPHYSICS, 57(11), 1396–1408 (1992).
!> http://dx.doi.org/10.1190/1.1443207 \n\n
!>
!>   Pressures 5-100 MPa, Temperature 20-350°C, Salinity <=320 g/L\n \n
!>
!>  CODE VERIFICATION:\n
!>   INPUT:  TEMP = 298.15K  P =0.1013 MPa  S = 0.25 g/g      OUTPUT: RHO = 1187.35 kg/m3\n
!>   INPUT:  TEMP = 393.15K  P =   30 MPa   S = 0.10 g/g      OUTPUT: RHO = 1027.06 kg/m3\n\n
!>
!> ARGUMENTS NAME    TYPE    UNITS           DESCRIPTION\n
!>     INPUT:        Temp  Real    T                 C       Temperature \n
!>                         Real    P         Pa      Pressure\n
!>                         Real    S         g/g     Salinity in mass fraction\n
!>    OUTPUT:        LABEL            RHO            Real     kg/m3  Density of brine \n
DOUBLE PRECISION FUNCTION g_RHOF(i, j, k, ismpl, rhof)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_FLOW
  IMPLICIT NONE
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Temperature (degC)
  DOUBLE PRECISION :: t
  DOUBLE PRECISION :: g_t
! Pressure (MPa)
  DOUBLE PRECISION :: p
  DOUBLE PRECISION :: g_p
! Salinity (mol/L)
  DOUBLE PRECISION :: s
  DOUBLE PRECISION :: g_s
! Salinity fraction (g/L)
  DOUBLE PRECISION :: sr
  DOUBLE PRECISION :: g_sr
! Molar mass of NaCl [g/mol]
! double precision, parameter :: mmnacl = 58.44277d0
  DOUBLE PRECISION, PARAMETER :: mmnacl=58.44d0
! Pure water density (kg/m3)
  DOUBLE PRECISION :: rw
  DOUBLE PRECISION :: g_rw
  DOUBLE PRECISION, EXTERNAL :: RHOW
	double precision, external :: g_rhow
! Pure water density (g/cm3)
  DOUBLE PRECISION :: rw_gcm3
  DOUBLE PRECISION :: g_rw_gcm3
! Fluid density (g/cm3)
  DOUBLE PRECISION :: rhof_gcm3
  DOUBLE PRECISION :: g_rhof_gcm3
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: temp1
  DOUBLE PRECISION :: rhof
! Local Temperature (degC)
  g_t = g_temp(i, j, k, ismpl)
  t = temp(i, j, k, ismpl)
! Local Pressure [MPa]
  g_p = pa_conv1*g_pres(i, j, k, ismpl)
  p = pres(i, j, k, ismpl)*pa_conv1
! Local salinity [mol/L]
  g_s = g_tsal(i, j, k, ismpl)
  s = tsal(i, j, k, ismpl)
! Pure water density [kg/m3]
  g_rw = g_RHOW(p, g_p, t, g_t, rw)
  IF (s .LE. 0.0d0) THEN
    g_rhof = g_rw
    rhof = rw
  ELSE
! mol/L (Molarity) > g/g (Mass fraCtion)
    temp0 = s/(rw+mmnacl*s)
    g_sr = mmnacl*(g_s-temp0*(g_rw+mmnacl*g_s))/(rw+mmnacl*s)
    sr = mmnacl*temp0
! Pure water density [g/cm3]
    g_rw_gcm3 = g_rw/1.0d3
    rw_gcm3 = rw/1.0d3
! Batzle, Equation (27b), densities in g/cm3
    temp0 = 3.0d0*t - 3.3d3*sr + 47.0d0*p*sr - 13.0d0*p + 80.0d0
    temp1 = 0.44d0*sr + 1.0d-6*(3.0d2*p-2.4d3*p*sr+t*temp0) + 0.668d0
    g_rhof_gcm3 = g_rw_gcm3 + temp1*g_sr + sr*(0.44d0*g_sr+&
&     1.0d-6*(3.0d2*g_p-2.4d3*(sr*g_p+p*g_sr)+temp0*g_t+t*(3.0d0&
&     *g_t-3.3d3*g_sr+47.0d0*(sr*g_p+p*g_sr)-13.0d0*g_p)))
    rhof_gcm3 = rw_gcm3 + sr*temp1
! Fluid density [kg/m3]
    g_rhof = 1.0d3*g_rhof_gcm3
    rhof = rhof_gcm3*1.0d3
  END IF
  RETURN
END FUNCTION g_RHOF

