!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of set_hcoefrs in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *d *e *f *g *temp *w *headold
!                *x *propunit *tsal *pres *a *b *c
!   with respect to varying inputs: *d *e *f *g *temp *w *headold
!                *x *propunit *tsal *pres *a *b *c
!   Plus diff mem management of: d:in e:in f:in g:in temp:in w:in
!                headold:in x:in propunit:in tsal:in pres:in simtime:in
!                a:in b:in c:in
!>    @brief calculate right hand side for the head equation
!>    @param[in] ismpl local sample index
!>    @details
!> calculate right hand side for the head equation\n
!> coefficients are stored as vectors in the diagonals a-g (d center) and rhs in w.\n
SUBROUTINE SET_HCOEFRS_AD(ismpl)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_GENRLC
  USE MOD_FLOW
  use mod_time

  USE MOD_TIME_AD

  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  DOUBLE PRECISION :: src, deltf, sijk
  DOUBLE PRECISION :: src_ad, sijk_ad
  EXTERNAL BUOY, COMPF, COMPM, RHOF, POR, DELTAT, &
&     HSTOR, VISF
  EXTERNAL BUOY_AD, HSTOR_AD0
! INTEGER c1, c2, c3, c4
  DOUBLE PRECISION :: BUOY, COMPF, COMPM, RHOF, POR, &
& DELTAT, HSTOR, VISF
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1_ad
  INTEGER :: arg1
  INTEGER :: branch
  deltf = DELTAT(simtime(ismpl), ismpl)
! rhs: sources
  IF (transient .AND. tr_switch(ismpl)) THEN
    DO k=1,k0
      DO j=1,j0
        DO i=1,i0
!             buoyancy
          IF (k .LT. k0) THEN
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          IF (k .GT. 1) THEN
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          CALL PUSHREAL8(sijk)
          sijk = HSTOR(i, j, k, ismpl)
        END DO
      END DO
    END DO
    DO k=k0,1,-1
      DO j=j0,1,-1
        DO i=i0,1,-1
          w_ad(i, j, k, ismpl) = w_ad(i, j, k, ismpl)/thetaf
          x_ad(i, j, k, ismpl) = x_ad(i, j, k, ismpl) - (1.0d0-thetaf)*&
&           w_ad(i, j, k, ismpl)
          headold_ad(i+(j-1)*i0+(k-1)*i0*j0, cgen_time, ismpl) = &
&           headold_ad(i+(j-1)*i0+(k-1)*i0*j0, cgen_time, ismpl) - sijk*&
&           w_ad(i, j, k, ismpl)/deltf
          sijk_ad = -(headold(i+(j-1)*i0+(k-1)*i0*j0, cgen_time, ismpl)*&
&           w_ad(i, j, k, ismpl)/deltf) - d_ad(i, j, k, ismpl)/(deltf*&
&           thetaf)
          src_ad = -w_ad(i, j, k, ismpl)
          CALL POPREAL8(sijk)
          CALL HSTOR_AD0(i, j, k, ismpl, sijk_ad)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            result1_ad = -(src_ad/delz(k))
            arg1 = k - 1
            CALL BUOY_AD(i, j, arg1, ismpl, result1_ad)
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            result1_ad = src_ad/delz(k)
            CALL BUOY_AD(i, j, k, ismpl, result1_ad)
          END IF
        END DO
      END DO
    END DO
    CALL OMP_MVP_AD(i0, j0, k0, headold(1, cgen_time, ismpl), headold_ad&
&             (1, cgen_time, ismpl), x(1, 1, 1, ismpl), x_ad(1, 1, 1, &
&             ismpl), a(1, 1, 1, ismpl), a_ad(1, 1, 1, ismpl), b(1, 1, 1&
&             , ismpl), b_ad(1, 1, 1, ismpl), c(1, 1, 1, ismpl), c_ad(1&
&             , 1, 1, ismpl), d(1, 1, 1, ismpl), d_ad(1, 1, 1, ismpl), e&
&             (1, 1, 1, ismpl), e_ad(1, 1, 1, ismpl), f(1, 1, 1, ismpl)&
&             , f_ad(1, 1, 1, ismpl), g(1, 1, 1, ismpl), g_ad(1, 1, 1, &
&             ismpl))
  ELSE
! - - - - - - - - steady state  - - - - - - - - - - - - - - - - - - - - -
    DO k=1,k0
      DO j=1,j0
        DO i=1,i0
! buoyancy  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
          IF (k .LT. k0) THEN
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          IF (k .GT. 1) THEN
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
        END DO
      END DO
    END DO
    DO k=k0,1,-1
      DO j=j0,1,-1
        DO i=i0,1,-1
          src_ad = -w_ad(i, j, k, ismpl)
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            result1_ad = -(src_ad/delz(k))
            arg1 = k - 1
            CALL BUOY_AD(i, j, arg1, ismpl, result1_ad)
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            result1_ad = src_ad/delz(k)
            CALL BUOY_AD(i, j, k, ismpl, result1_ad)
          END IF
        END DO
      END DO
    END DO
  END IF
END SUBROUTINE SET_HCOEFRS_AD

