!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of visf in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *tsal *pres visf
!   with respect to varying inputs: *temp *tsal *pres
!   Plus diff mem management of: temp:in tsal:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief calculates viscosity of aqueous NaCl solutions
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return  visc
!> @details
!> Source:\n
!> Batzle, M., & Wang, Z., Seismic properties of pore fluids,
!> GEOPHYSICS, 57(11), 1396–1408 (1992).
!> http://dx.doi.org/10.1190/1.1443207 \n\n
!>\n
!>   Pressures 5-100 MPa, Temperature 20-350°C, Salinity <=320 g/L\n
!>\n
SUBROUTINE VISF_AD(i, j, k, ismpl, visf_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_FLOW
  IMPLICIT NONE
  double precision :: visf_adv
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Temperature (degC)
  DOUBLE PRECISION :: t
  DOUBLE PRECISION :: t_ad
! Pressure (MPa)
  DOUBLE PRECISION :: p
  DOUBLE PRECISION :: p_ad
! Salinity (mol/L)
  DOUBLE PRECISION :: s
  DOUBLE PRECISION :: s_ad
! Mass fraction [-]
  DOUBLE PRECISION :: sr
  DOUBLE PRECISION :: sr_ad
! Pure water density (kg/m3)
  DOUBLE PRECISION :: rw
  DOUBLE PRECISION :: rw_ad
  DOUBLE PRECISION, EXTERNAL :: RHOW
! Pure water viscosity [Pa s]
  DOUBLE PRECISION, EXTERNAL :: VISW
! Molar mass of NaCl [g/mol]
! double precision, parameter :: mmnacl = 58.44277d0
  DOUBLE PRECISION, PARAMETER :: mmnacl=58.44d0
! Viscosity [cP]
  DOUBLE PRECISION :: visf_cp
  DOUBLE PRECISION :: visf_cp_ad
  INTRINSIC EXP
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: temp1
  DOUBLE PRECISION :: temporary_ad0
  DOUBLE PRECISION :: temp2
  DOUBLE PRECISION :: temp3
  DOUBLE PRECISION :: temporary_ad1
  DOUBLE PRECISION :: visf
! Pressure [MPa]
  p = pres(i, j, k, ismpl)*pa_conv1
! Temperature [degC]
  t = temp(i, j, k, ismpl)
! Salinity [mol/L]
  s = tsal(i, j, k, ismpl)
  IF (s .LE. 0.d0) THEN
    CALL VISW_AD0(p, p_ad, t, t_ad, visf_adv)
    s_ad = 0.D0
  ELSE
! Pure water density [kg/m3]
    rw = RHOW(p, t)
! mol/L (Molarity) > [g/L] = [kg/m3; ]g/g (mass fraction)      
    sr = s*mmnacl/(rw+s*mmnacl)
! Viscosity formula after Batzle & Wang [cP] 
! Conversion of viscosity from [cP] to [Pa s]
    visf_cp_ad = 1.0d-3*visf_adv
    temp1 = t**0.8d0
    temp0 = sr**0.8d0 - 0.17d0
    temp2 = 0.42d0*(temp0*temp0) + 0.045d0
    temp3 = -(temp2*temp1)
    temporary_ad1 = EXP(temp3)*(91.9d0*sr**3+1.65d0)*visf_cp_ad
    sr_ad = (3*sr**2*91.9d0*EXP(temp3)+0.333d0)*visf_cp_ad - 0.8d0*sr**(&
&     -0.2D0)*2*temp0*0.42d0*temp1*temporary_ad1
    t_ad = -(0.8d0*t**(-0.2D0)*temp2*temporary_ad1)
    temporary_ad = mmnacl*sr_ad/(rw+mmnacl*s)
    temporary_ad0 = -(s*temporary_ad/(rw+mmnacl*s))
    s_ad = temporary_ad + mmnacl*temporary_ad0
    rw_ad = temporary_ad0
    p_ad = 0.D0
    CALL RHOW_AD0(p, p_ad, t, t_ad, rw_ad)
  END IF
  tsal_ad(i, j, k, ismpl) = tsal_ad(i, j, k, ismpl) + s_ad
  temp_ad(i, j, k, ismpl) = temp_ad(i, j, k, ismpl) + t_ad
  pres_ad(i, j, k, ismpl) = pres_ad(i, j, k, ismpl) + pa_conv1*p_ad
END SUBROUTINE VISF_AD

