!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of gi in forward (tangent) mode:
!   variations   of useful results: gi
!   with respect to varying inputs: *temp *propunit *tsal *pres
!   Plus diff mem management of: temp:in propunit:in tsal:in pres:in
!>    @brief average  conductivities on cell faces in x direction
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return x  conductivity (m/(Pa s))
DOUBLE PRECISION FUNCTION g_GI(i, j, k, ismpl, gi)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_FLOW
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL KX, RHOF, VISF
  EXTERNAL g_KX, g_VISF
  DOUBLE PRECISION :: f1, f2, prod, summ, KX, RHOF, VISF
  DOUBLE PRECISION :: g_f1, g_f2, g_prod, g_summ, g_KX, &
& g_VISF
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: g_result2
  DOUBLE PRECISION :: gi
  gi = 0.d0
  IF (i0 .GT. 1 .AND. i .LT. i0) THEN
    g_result1 = g_KX(i, j, k, ismpl, result1)
    g_result2 = g_VISF(i, j, k, ismpl, result2)
    g_f1 = (g_result1-result1*g_result2/result2)/result2
    f1 = result1/result2
    g_result1 = g_KX(i + 1, j, k, ismpl, result1)
    g_result2 = g_VISF(i + 1, j, k, ismpl, result2)
    g_f2 = (g_result1-result1*g_result2/result2)/result2
    f2 = result1/result2
    g_prod = f2*g_f1 + f1*g_f2
    prod = f1*f2
    g_summ = delx(i+1)*g_f1 + delx(i)*g_f2
    summ = f1*delx(i+1) + f2*delx(i)
    IF (summ .GT. 0.d0) THEN
      g_gi = 2.d0*(g_prod-prod*g_summ/summ)/summ
      gi = 2.d0*prod/summ
    ELSE
      g_gi = 0.D0
    END IF
  ELSE
    g_gi = 0.D0
  END IF
  RETURN
END FUNCTION g_GI

