!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of visf in forward (tangent) mode:
!   variations   of useful results: visf
!   with respect to varying inputs: *temp *tsal *pres
!   Plus diff mem management of: temp:in tsal:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief calculates viscosity of aqueous NaCl solutions
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return  visc
!> @details
!> Source:\n
!> Batzle, M., & Wang, Z., Seismic properties of pore fluids,
!> GEOPHYSICS, 57(11), 1396–1408 (1992).
!> http://dx.doi.org/10.1190/1.1443207 \n\n
!>\n
!>   Pressures 5-100 MPa, Temperature 20-350°C, Salinity <=320 g/L\n
!>\n
DOUBLE PRECISION FUNCTION g_VISF(i, j, k, ismpl, visf)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_FLOW
  IMPLICIT NONE
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Temperature (degC)
  DOUBLE PRECISION :: t
  DOUBLE PRECISION :: g_t
! Pressure (MPa)
  DOUBLE PRECISION :: p
  DOUBLE PRECISION :: g_p
! Salinity (mol/L)
  DOUBLE PRECISION :: s
  DOUBLE PRECISION :: g_s
! Mass fraction [-]
  DOUBLE PRECISION :: sr
  DOUBLE PRECISION :: g_sr
! Pure water density (kg/m3)
  DOUBLE PRECISION :: rw
  DOUBLE PRECISION :: g_rw
  DOUBLE PRECISION, EXTERNAL :: RHOW
! Pure water viscosity [Pa s]
  DOUBLE PRECISION, EXTERNAL :: VISW
  DOUBLE PRECISION, EXTERNAL :: g_VISW
	double precision, external :: g_rhow
! Molar mass of NaCl [g/mol]
! double precision, parameter :: mmnacl = 58.44277d0
  DOUBLE PRECISION, PARAMETER :: mmnacl=58.44d0
! Viscosity [cP]
  DOUBLE PRECISION :: visf_cp
  DOUBLE PRECISION :: g_visf_cp
  INTRINSIC EXP
  DOUBLE PRECISION :: arg1
  DOUBLE PRECISION :: g_arg1
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: temp1
  DOUBLE PRECISION :: visf
! Pressure [MPa]
  g_p = pa_conv1*g_pres(i, j, k, ismpl)
  p = pres(i, j, k, ismpl)*pa_conv1
! Temperature [degC]
  g_t = g_temp(i, j, k, ismpl)
  t = temp(i, j, k, ismpl)
! Salinity [mol/L]
  g_s = g_tsal(i, j, k, ismpl)
  s = tsal(i, j, k, ismpl)
  IF (s .LE. 0.d0) THEN
    g_visf = g_VISW(p, g_p, t, g_t, visf)
  ELSE
! Pure water density [kg/m3]
    g_rw = g_RHOW(p, g_p, t, g_t, rw)
! mol/L (Molarity) > [g/L] = [kg/m3; ]g/g (mass fraction)      
    temp0 = s/(rw+mmnacl*s)
    g_sr = mmnacl*(g_s-temp0*(g_rw+mmnacl*g_s))/(rw+mmnacl*s)
    sr = mmnacl*temp0
! Viscosity formula after Batzle & Wang [cP] 
    temp0 = t**0.8d0
    temp1 = 0.42d0*((sr**0.8d0-0.17d0)*(sr**0.8d0-0.17d0)) + 0.045d0
    g_arg1 = -(temp0*0.42d0*2*(sr**0.8d0-0.17d0)*0.8d0*sr**(-0.2D0)*&
&     g_sr+temp1*0.8d0*t**(-0.2D0)*g_t)
    arg1 = -(temp1*temp0)
    temp1 = EXP(arg1)
    temp0 = 91.9d0*(sr*sr*sr) + 1.65d0
    g_visf_cp = (temp1*91.9d0*3*sr**2+0.333d0)*g_sr + temp0*EXP(arg1&
&     )*g_arg1
    visf_cp = 0.333d0*sr + temp0*temp1 + 0.1d0
! Conversion of viscosity from [cP] to [Pa s]
    g_visf = 1.0d-3*g_visf_cp
    visf = visf_cp*1.0d-3
  END IF
  RETURN
END FUNCTION g_VISF

