!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of visw in forward (tangent) mode:
!   variations   of useful results: visw
!   with respect to varying inputs: p t
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief rhof(i,j,k,ismpl) calculates the viscosity in (in Pa s) of pure water
!> @param[in] p cell pressure [MPa]
!> @param[in] t temperature [degC]
!> @return visw  [Pa s]
!> @details
!> rhof(i,j,k,ismpl) calculates the viscosity in (in Pa s) of  pure water,\n
!> given temperature (t, in C), and pressure (p,in Pa) at node(i,j,k)\n\n
!>
!>  Main source Zyvoloski1997: \n
!>
!> Zyvoloski, G.A., Robinson, B.A., Dash, Z.V., & Trease, L.L. Summary
!> of the models and methods for the FEHM application - a
!> finite-element heat- and mass-transfer code. United
!> States. doi:10.2172/565545. \n \n
!>
!> See Section 8.4.3. of Zyvoloski1997 for an explanation of the
!> "Rational function approximation" used in this subroutine. \n \n
!> The approximation uses the table of coefficients in Appendix 10 of
!> Zyvoloski1997.\n
!>
!> Alternative source (same text, more modern, without doi): \n
!> https://fehm.lanl.gov/orgs/ees/fehm/pdfs/fehm_mms.pdf \n \n
!>
!> The table of coefficients from Zyvoloski1997 describes the physical
!> values found in Haar1984: \n
!>
!> Lester Haar, John Gallagher, George Kell, NBS/NRC Steam Tables:
!> Thermodynamic and Transport Properties and Computer Programs for
!> Vapor and Liquid States of Water in SI Units, Hemisphere Publishing
!> Corporation, Washington, 1984. \n \n
!>
!>    range of validity:\n
!>    - pressures   0.001 - 110 MPa,\n
!>    - temperature   15 - 360 degC\n
DOUBLE PRECISION FUNCTION g_VISW(p, g_p, t, g_t, visw)
  IMPLICIT NONE
! Temperature (degC)
  DOUBLE PRECISION, INTENT(IN) :: t
  DOUBLE PRECISION, INTENT(IN) :: g_t
! Pressure (MPa)
  DOUBLE PRECISION, INTENT(IN) :: p
  DOUBLE PRECISION, INTENT(IN) :: g_p
! Coefficients of numerator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: y0=0.17409149d-02
  DOUBLE PRECISION, PARAMETER :: y1=0.18894882d-04
  DOUBLE PRECISION, PARAMETER :: y2=-0.66439332d-07
  DOUBLE PRECISION, PARAMETER :: y3=-0.23122388d-09
  DOUBLE PRECISION, PARAMETER :: y4=-0.31534914d-05
  DOUBLE PRECISION, PARAMETER :: y5=0.11120716d-07
  DOUBLE PRECISION, PARAMETER :: y6=-0.48576020d-10
  DOUBLE PRECISION, PARAMETER :: y7=0.28006861d-07
  DOUBLE PRECISION, PARAMETER :: y8=0.23225035d-09
  DOUBLE PRECISION, PARAMETER :: y9=0.47180171d-10
! Coefficients of denominator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: z0=0.10000000d+01
  DOUBLE PRECISION, PARAMETER :: z1=0.10523153d-01
  DOUBLE PRECISION, PARAMETER :: z2=-0.22658391d-05
  DOUBLE PRECISION, PARAMETER :: z3=-0.31796607d-06
  DOUBLE PRECISION, PARAMETER :: z4=0.29869141d-01
  DOUBLE PRECISION, PARAMETER :: z5=0.21844248d-03
  DOUBLE PRECISION, PARAMETER :: z6=-0.87658855d-06
  DOUBLE PRECISION, PARAMETER :: z7=0.41690362d-03
  DOUBLE PRECISION, PARAMETER :: z8=-0.25147022d-05
  DOUBLE PRECISION, PARAMETER :: z9=0.22144660d-05
! Monomials of temperature and pressure
  DOUBLE PRECISION :: t2, t3
  DOUBLE PRECISION :: g_t2, g_t3
  DOUBLE PRECISION :: p2, p3, p4
  DOUBLE PRECISION :: g_p2, g_p3
  DOUBLE PRECISION :: tp, t2p, tp2
  DOUBLE PRECISION :: g_tp, g_t2p, g_tp2
! Numerator and denominator of rational function approximation
  DOUBLE PRECISION :: ta, tb
  DOUBLE PRECISION :: g_ta, g_tb
  DOUBLE PRECISION :: visw
! Compute monomials in pressure and temperature
  g_p2 = 2*p*g_p
  p2 = p*p
  g_p3 = p*g_p2 + p2*g_p
  p3 = p2*p
  p4 = p3*p
  g_t2 = 2*t*g_t
  t2 = t*t
  g_t3 = t*g_t2 + t2*g_t
  t3 = t2*t
  g_tp = t*g_p + p*g_t
  tp = p*t
  g_tp2 = p2*g_t + t*g_p2
  tp2 = t*p2
  g_t2p = p*g_t2 + t2*g_p
  t2p = t2*p
! Numerator of rational function approximation
  g_ta = y1*g_p + y2*g_p2 + y3*g_p3 + y4*g_t + y5*g_t2 + y6*&
&   g_t3 + y7*g_tp + y8*g_tp2 + y9*g_t2p
  ta = y0 + y1*p + y2*p2 + y3*p3 + y4*t + y5*t2 + y6*t3 + y7*tp + y8*tp2&
&   + y9*t2p
! Denominator of rational function approximation
  g_tb = z1*g_p + z2*g_p2 + z3*g_p3 + z4*g_t + z5*g_t2 + z6*&
&   g_t3 + z7*g_tp + z8*g_tp2 + z9*g_t2p
  tb = z0 + z1*p + z2*p2 + z3*p3 + z4*t + z5*t2 + z6*t3 + z7*tp + z8*tp2&
&   + z9*t2p
! Viscosity
  g_visw = (g_ta-ta*g_tb/tb)/tb
  visw = ta/tb
  RETURN
END FUNCTION g_VISW

