!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of get_tpbcalbe in forward (tangent) mode:
!   variations   of useful results: mbeta malfa
!   with respect to varying inputs: *bcperiod
!   Plus diff mem management of: bcperiod:in simtime:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief time depended boundary condition modificators
!>    @param[out] malfa alfa modificator
!>    @param[out] mbeta beta modificator
!>    @param[in] tpbcu time period BC table index
!>    @param[in] ismpl local sample index
!>    @details
!> "GET Time Periods Boundary Condition ALfa & BEta"\n
!> get the alfa and beta modificators for time dependend bc-values\n
SUBROUTINE g_GET_TPBCALBE(malfa, g_malfa, mbeta, g_mbeta, tpbcu, &
& ismpl)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_TIME

  USE g_MOD_TIME

  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: k
  INTEGER :: tpbcu, imt
  DOUBLE PRECISION :: malfa, mbeta, mtime
  DOUBLE PRECISION :: g_malfa, g_mbeta
  INTRINSIC ABS
  INTEGER :: abs0
!       default - when not time depended
  malfa = 0.0d0
  mbeta = 1.0d0
!
  IF (tpbcu .GT. 0) THEN
    k = 0
    imt = 0
    g_mbeta = 0.D0
    g_malfa = 0.D0
!         next bc-tp entry
 100 imt = imt + 1
    mtime = bcperiod(imt, 1, tpbcu, ismpl)
    IF (mtime .LE. simtime(ismpl)) THEN
      g_malfa = g_bcperiod(imt, 2, tpbcu, ismpl)
      malfa = bcperiod(imt, 2, tpbcu, ismpl)
      g_mbeta = g_bcperiod(imt, 3, tpbcu, ismpl)
      mbeta = bcperiod(imt, 3, tpbcu, ismpl)
!           save index of the valid start time
      k = imt
    END IF
!
!         !!! this IF statement (with the GOTO) needs to be outside of the
!             other "mtime<=simtime(ismpl)" scopes, to generate reverse-mode code !!!
    IF (mtime .LE. simtime(ismpl) .AND. imt .LT. ibcperiod(tpbcu)) GOTO &
&      100
    IF (k .GT. 0) THEN
      IF (.NOT.lbcperiod(k, tpbcu)) THEN
        IF (tpbcu .GE. 0.) THEN
          abs0 = tpbcu
        ELSE
          abs0 = -tpbcu
        END IF
!              disable this BC (switched off)
        tpbcu = -abs0
      END IF
    END IF
  ELSE
    g_mbeta = 0.D0
    g_malfa = 0.D0
  END IF
!
  RETURN
END SUBROUTINE g_GET_TPBCALBE

