!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of set_pcoef in forward (tangent) mode:
!   variations   of useful results: *d *e *f *g *a *b *c
!   with respect to varying inputs: *d *e *f *g *temp *propunit
!                *tsal *pres *a *b *c
!   Plus diff mem management of: d:in e:in f:in g:in temp:in propunit:in
!                tsal:in pres:in a:in b:in c:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief calculate coefficents for the head equation
!>    @param[in] ismpl local sample index
!>    @details
!> calculate coefficents for the head equation\n
!> coefficients are stored as vectors in the diagonals a-g (d center) and rhs in w.\n
SUBROUTINE g_SET_PCOEF(ismpl)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_GENRLC
  USE MOD_FLOW
  USE MOD_TIME

  USE g_MOD_TIME

  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL FI, FJ, FK
  EXTERNAL g_FI, g_FJ, g_FK
  DOUBLE PRECISION :: FI, FJ, FK
  DOUBLE PRECISION :: g_FI, g_FJ, g_FK
  EXTERNAL DUMMY
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
!$OMP master
  IF (linfos(3) .GE. 2) WRITE(*, *) ' ... fcoef'
!$OMP end master
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$OMP do schedule(static) collapse(3)
  DO k=1,k0
    DO j=1,j0
      DO i=1,i0
        IF (i0 .GT. 1) THEN
          IF (i .LT. i0) THEN
            g_result1 = g_FI(i, j, k, ismpl, result1)
            g_e(i, j, k, ismpl) = g_result1/delx(i)
            e(i, j, k, ismpl) = result1/delx(i)
          END IF
          IF (i .GT. 1) THEN
            g_result1 = g_FI(i - 1, j, k, ismpl, result1)
            g_c(i, j, k, ismpl) = g_result1/delx(i)
            c(i, j, k, ismpl) = result1/delx(i)
          END IF
        END IF
        IF (j0 .GT. 1) THEN
          IF (j .LT. j0) THEN
            g_result1 = g_FJ(i, j, k, ismpl, result1)
            g_f(i, j, k, ismpl) = g_result1/dely(j)
            f(i, j, k, ismpl) = result1/dely(j)
          END IF
          IF (j .GT. 1) THEN
            g_result1 = g_FJ(i, j - 1, k, ismpl, result1)
            g_b(i, j, k, ismpl) = g_result1/dely(j)
            b(i, j, k, ismpl) = result1/dely(j)
          END IF
        END IF
        IF (k0 .GT. 1) THEN
          IF (k .LT. k0) THEN
            g_result1 = g_FK(i, j, k, ismpl, result1)
            g_g(i, j, k, ismpl) = g_result1/delz(k)
            g(i, j, k, ismpl) = result1/delz(k)
          END IF
          IF (k .GT. 1) THEN
            g_result1 = g_FK(i, j, k - 1, ismpl, result1)
            g_a(i, j, k, ismpl) = g_result1/delz(k)
            a(i, j, k, ismpl) = result1/delz(k)
          END IF
        END IF
        g_d(i, j, k, ismpl) = -g_e(i, j, k, ismpl) - g_c(i, j, k, &
&         ismpl) - g_f(i, j, k, ismpl) - g_b(i, j, k, ismpl) - g_g&
&         (i, j, k, ismpl) - g_a(i, j, k, ismpl)
        d(i, j, k, ismpl) = -(e(i, j, k, ismpl)+c(i, j, k, ismpl)+f(i, j&
&         , k, ismpl)+b(i, j, k, ismpl)+g(i, j, k, ismpl)+a(i, j, k, &
&         ismpl))
      END DO
    END DO
  END DO
!$OMP end do nowait
  RETURN
END SUBROUTINE g_SET_PCOEF

