!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of set_tcoefrs in forward (tangent) mode:
!   variations   of useful results: *d *w *x
!   with respect to varying inputs: *d *e *f *g *temp *w *x *tempold
!                *propunit *tsal *pres *a *b *c
!   Plus diff mem management of: d:in e:in f:in g:in temp:in w:in
!                x:in tempold:in propunit:in tsal:in pres:in simtime:in
!                a:in b:in c:in
!>    @brief coefficents for the heat equation (here right hand side)
!>    @param[in] ismpl local sample index
!>    @details
!> calculate coefficents for the heat equation\n
!> coefficients are stored as vectors in the diagonals a-g (d center) and rhs in w.\n
SUBROUTINE g_SET_TCOEFRS(ismpl)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_GENRLC
  USE MOD_TEMP
  USE MOD_TIME

  USE g_MOD_TIME

  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  DOUBLE PRECISION :: deltt, rce
  DOUBLE PRECISION :: g_rce
  EXTERNAL RHOCEFF, POR, QT, DELTAT
  EXTERNAL g_RHOCEFF, g_POR
! INTEGER c1, c2, c3, c4
  DOUBLE PRECISION :: RHOCEFF, POR, QT, DELTAT
  DOUBLE PRECISION :: g_RHOCEFF, g_POR
  EXTERNAL DUMMY
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: temp0
  deltt = DELTAT(simtime(ismpl), ismpl)
! - - rhs: sources, also terms for transient caolculations - - - - - - - - -
  IF (transient .AND. tr_switch(ismpl)) THEN
! - - - - - - - transient  - - - - - - - - - - - - - - - - - - - - - - - - - -
    CALL g_OMP_MVP(i0, j0, k0, tempold(1, cgen_time, ismpl), &
&              g_tempold(1, cgen_time, ismpl), x(1, 1, 1, ismpl), &
&              g_x(1, 1, 1, ismpl), a(1, 1, 1, ismpl), g_a(1, 1, 1, &
&              ismpl), b(1, 1, 1, ismpl), g_b(1, 1, 1, ismpl), c(1, 1&
&              , 1, ismpl), g_c(1, 1, 1, ismpl), d(1, 1, 1, ismpl), &
&              g_d(1, 1, 1, ismpl), e(1, 1, 1, ismpl), g_e(1, 1, 1, &
&              ismpl), f(1, 1, 1, ismpl), g_f(1, 1, 1, ismpl), g(1, 1&
&              , 1, ismpl), g_g(1, 1, 1, ismpl))
!$OMP do schedule(static) collapse(3)
    DO k=1,k0
      DO j=1,j0
        DO i=1,i0
!                 add  solid and fluid heat production, boundary terms
          g_rce = g_RHOCEFF(i, j, k, ismpl, rce)
          g_d(i, j, k, ismpl) = g_d(i, j, k, ismpl) - g_rce/(deltt&
&           *thetat)
          d(i, j, k, ismpl) = d(i, j, k, ismpl) - rce/(deltt*thetat)
          g_result1 = g_POR(i, j, k, ismpl, result1)
          temp0 = tempold(i+(j-1)*i0+(k-1)*i0*j0, cgen_time, ismpl)
          g_w(i, j, k, ismpl) = g_w(i, j, k, ismpl) - rce*&
&           g_tempold(i+(j-1)*i0+(k-1)*i0*j0, cgen_time, ismpl)/deltt &
&           - temp0*g_rce/deltt - (1.d0-thetat)*g_x(i, j, k, ismpl) &
&           - hpf*g_result1
          w(i, j, k, ismpl) = w(i, j, k, ismpl) - temp0*(rce/deltt) - (&
&           1.d0-thetat)*x(i, j, k, ismpl) - hpf*result1
          g_w(i, j, k, ismpl) = g_w(i, j, k, ismpl)/thetat
          w(i, j, k, ismpl) = w(i, j, k, ismpl)/thetat
        END DO
      END DO
    END DO
!$OMP    end do nowait
  ELSE
! - - - - - - - - steady state - - - - - - - - - - - - - - - - - - - - - 
!$OMP do schedule(static) collapse(3)
    DO k=1,k0
      DO j=1,j0
        DO i=1,i0
!                 solid and fluid heat production
          g_result1 = g_POR(i, j, k, ismpl, result1)
          g_w(i, j, k, ismpl) = g_w(i, j, k, ismpl) - hpf*&
&           g_result1
          w(i, j, k, ismpl) = w(i, j, k, ismpl) - hpf*result1
        END DO
      END DO
    END DO
!$OMP    end do nowait
  END IF
  RETURN
END SUBROUTINE g_SET_TCOEFRS

