!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!>    @brief reinjection "dummy" routine, no "reinjection" functionality
!>    @param[in] ismpl local sample index
SUBROUTINE calc_user_ad(ismpl)
  use arrays
  USE ARRAYS_AD
  USE MOD_GENRL
  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i
  INTRINSIC INT
  IF (linfos(3) .GE. 2) WRITE(*, *) ' ... calc_user'
!     Dummy body
  i = INT(head(1, 1, 1, ismpl))
  RETURN
END SUBROUTINE calc_user_ad

