!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of lx in forward (tangent) mode:
!   variations   of useful results: lx
!   with respect to varying inputs: *propunit
!   Plus diff mem management of: propunit:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief calculates effective thermal conductivity of the cell
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return  thermal conductivity lx[W/(m*K)]
!> @details
!> calculates effective thermal conductivity of the two phase system
!> matrix-porosity .\n\n
!>
!> input:\n
!> porosity                            porlocal [-]\n
!> thermal conductivity of fluid           lamf [W/(m*K)]\n
!> thermal conductivity of matrix       lammref [W/(m*K)]\n
DOUBLE PRECISION FUNCTION g_LX(i, j, k, ismpl, lx)
  USE ARRAYS

  USE g_ARRAYS

  IMPLICIT NONE
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Local fluid thermal conductivity [W/(m*K)]
  DOUBLE PRECISION :: lamfluid
  DOUBLE PRECISION, EXTERNAL :: LAMF
! Matrix thermal conductivity [W/(m*K)]
  DOUBLE PRECISION :: lammref
  DOUBLE PRECISION :: g_lammref
! Local porosity [-]
  DOUBLE PRECISION, EXTERNAL :: POR
  DOUBLE PRECISION, EXTERNAL :: g_POR
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: pwy1
  DOUBLE PRECISION :: g_pwy1
  DOUBLE PRECISION :: pwr1
  DOUBLE PRECISION :: g_pwr1
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: g_result2
  DOUBLE PRECISION :: pwr2
  DOUBLE PRECISION :: g_pwr2
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: temp1
  DOUBLE PRECISION :: lx
! Local fluid thermal conductivity [W/(m*K)]
  lamfluid = LAMF(i, j, k, ismpl)
! Reference matrix thermal conductivity [W/(m*K)]
  temp0 = propunit(uindex(i, j, k), idx_an_lx, ismpl)
  temp1 = propunit(uindex(i, j, k), idx_lz, ismpl)
  g_lammref = temp0*g_propunit(uindex(i, j, k), idx_lz, ismpl) + &
&   temp1*g_propunit(uindex(i, j, k), idx_an_lx, ismpl)
  lammref = temp1*temp0
  g_result1 = g_POR(i, j, k, ismpl, result1)
  g_pwy1 = -g_result1
  pwy1 = 1.0d0 - result1
  temp1 = lammref**pwy1
  IF (lammref .LE. 0.0 .AND. (pwy1 .EQ. 0.0 .OR. pwy1 .NE. INT(pwy1))) &
& THEN
    g_pwr1 = 0.D0
  ELSE IF (lammref .LE. 0.0) THEN
    g_pwr1 = pwy1*lammref**(pwy1-1)*g_lammref
  ELSE
    g_pwr1 = pwy1*lammref**(pwy1-1)*g_lammref + temp1*LOG(lammref)*&
&     g_pwy1
  END IF
  pwr1 = temp1
  g_result2 = g_POR(i, j, k, ismpl, result2)
  temp1 = lamfluid**result2
  IF (lamfluid .LE. 0.0) THEN
    g_pwr2 = 0.D0
  ELSE
    g_pwr2 = temp1*LOG(lamfluid)*g_result2
  END IF
  pwr2 = temp1
  g_lx = pwr2*g_pwr1 + pwr1*g_pwr2
  lx = pwr1*pwr2
  RETURN
END FUNCTION g_LX

