!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of ti in forward (tangent) mode:
!   variations   of useful results: ti
!   with respect to varying inputs: *propunit
!   Plus diff mem management of: propunit:in
!>    @brief harmonic mean Kx on cell faces in x direction over delx*
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return x hydraulic conductivity over delx*  (1/s)
!>    @details
!>    Compute the harmonic mean of Kx on the cell face in positive
!>    x-direction from the current node (i, j, k) divided by the
!>    x-distance of the current node (i, j, k) to the neighboring node
!>    (i+1, j, k).
!>
!>    delx* = 0.5 ( delx(i) + delx(i+1) )
!>
!>    Kx / delx* = [ 0.5*delx(i+1)/K(i+1) + 0.5*delx(i)/K(i) ]**-1
!>
!>               = [ ( 0.5* K(i)* delx(i+1) + 0.5*K(i+1)* delx(i) ) / ( K(i)*K(i+1) ) ]**-1
!>
!>               = [ ( 0.5 * summ ) / (prod) ]**-1 = 2.0*prod/summ
DOUBLE PRECISION FUNCTION g_TI(i, j, k, ismpl, ti)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_FLOW
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL KX, RHOF, VISF
  EXTERNAL g_KX
  DOUBLE PRECISION :: f1, f2, prod, summ, KX, RHOF, VISF
  DOUBLE PRECISION :: g_f1, g_f2, g_prod, g_summ, g_KX
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: result3
  DOUBLE PRECISION :: ti
  ti = 0.d0
  IF (i0 .GT. 1 .AND. i .LT. i0) THEN
    g_result1 = g_KX(i, j, k, ismpl, result1)
    result2 = RHOF(i, j, k, ismpl)
    result3 = VISF(i, j, k, ismpl)
    g_f1 = result2*grav*g_result1/result3
    f1 = result1*result2*grav/result3
    g_result1 = g_KX(i + 1, j, k, ismpl, result1)
    result2 = RHOF(i + 1, j, k, ismpl)
    result3 = VISF(i + 1, j, k, ismpl)
    g_f2 = result2*grav*g_result1/result3
    f2 = result1*result2*grav/result3
    g_prod = f2*g_f1 + f1*g_f2
    prod = f1*f2
    g_summ = delx(i+1)*g_f1 + delx(i)*g_f2
    summ = f1*delx(i+1) + f2*delx(i)
    IF (summ .GT. 0.d0) THEN
      g_ti = 2.d0*(g_prod-prod*g_summ/summ)/summ
      ti = 2.d0*prod/summ
    ELSE
      g_ti = 0.D0
    END IF
  ELSE
    g_ti = 0.D0
  END IF
  RETURN
END FUNCTION g_TI

