!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of tj in forward (tangent) mode:
!   variations   of useful results: tj
!   with respect to varying inputs: *propunit
!   Plus diff mem management of: propunit:in
!>    @brief harmonic mean Ky on cell faces in y direction over dely*
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return y hydraulic conductivity over dely*  (1/s)
!>    @details
!>    Compute the harmonic mean of Ky on the cell face in positive
!>    y-direction from the current node (i, j, k) divided by the
!>    y-distance of the current node (i, j, k) to the neighboring node
!>    (i, j+1, k).
!>
!>    dely* = 0.5 ( dely(j) + dely(j+1) )
!>
!>    Ky / dely* = [ 0.5*dely(j+1)/K(j+1) + 0.5*dely(j)/K(j) ]**-1
!>
!>               = [ ( 0.5* K(j)* dely(j+1) + 0.5*K(j+1)* dely(j) ) / ( K(j)*K(j+1) ) ]**-1
!>
!>               = [ ( 0.5 * summ ) / (prod) ]**-1 = 2.0*prod/summ
DOUBLE PRECISION FUNCTION g_TJ(i, j, k, ismpl, tj)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_FLOW
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL KY, RHOF, VISF
  EXTERNAL g_KY
  DOUBLE PRECISION :: f1, f2, prod, summ, KY, RHOF, VISF
  DOUBLE PRECISION :: g_f1, g_f2, g_prod, g_summ, g_KY
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: result3
  DOUBLE PRECISION :: tj
  tj = 0.d0
  IF (j0 .GT. 1 .AND. j .LT. j0) THEN
    g_result1 = g_KY(i, j, k, ismpl, result1)
    result2 = RHOF(i, j, k, ismpl)
    result3 = VISF(i, j, k, ismpl)
    g_f1 = result2*grav*g_result1/result3
    f1 = result1*result2*grav/result3
    g_result1 = g_KY(i, j + 1, k, ismpl, result1)
    result2 = RHOF(i, j + 1, k, ismpl)
    result3 = VISF(i, j + 1, k, ismpl)
    g_f2 = result2*grav*g_result1/result3
    f2 = result1*result2*grav/result3
    g_prod = f2*g_f1 + f1*g_f2
    prod = f1*f2
    g_summ = dely(j+1)*g_f1 + dely(j)*g_f2
    summ = f1*dely(j+1) + f2*dely(j)
    IF (summ .GT. 0.d0) THEN
      g_tj = 2.d0*(g_prod-prod*g_summ/summ)/summ
      tj = 2.d0*prod/summ
    ELSE
      g_tj = 0.D0
    END IF
  ELSE
    g_tj = 0.D0
  END IF
  RETURN
END FUNCTION g_TJ

