!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of check_domain in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *conc *pres
!   with respect to varying inputs: *temp *conc *pres
!   Plus diff mem management of: temp:in conc:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief domain of validity for module const
!>    @param[in] ismpl local sample index
!>    @details
!>    Checking whether pres/temp/(conc) are in domain of props
!>    validity. Version for property module const. \n
!>    \n
!>    For concentration, an error is thrown and the execution is
!>    stopped if the concentration is outside the physical values.
SUBROUTINE CHECK_DOMAIN_AD(ismpl)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_GENRLC
  USE MOD_CONC
  USE MOD_LINFOS
  IMPLICIT NONE
! Sample index
  INTEGER :: ismpl
! Iteration counters
  INTEGER :: i, j, k, l
! counters for the values outside domain of validity
! pres
  INTEGER :: icountp
! temp
  INTEGER :: icountt
! conc
  INTEGER :: icountc
! min/max boundaries of the domain of validity
! pres
  DOUBLE PRECISION, PARAMETER :: pmin=0.01d6
  DOUBLE PRECISION, PARAMETER :: pmax=110.0d6
! temp
  DOUBLE PRECISION, PARAMETER :: tmin=0.0d0
  DOUBLE PRECISION, PARAMETER :: tmax=350.0d0
! conc
  DOUBLE PRECISION, PARAMETER :: cmin=0.0d0
  DOUBLE PRECISION, PARAMETER :: cmax=1.0d5
! numerical boundary
  DOUBLE PRECISION, PARAMETER :: csmin=1.0d-30
! records the overall min/max of values if they are outside
! domain of validity
  DOUBLE PRECISION :: dpmax, dtmax, dcmax, dhmax
  DOUBLE PRECISION :: dpmin, dtmin, dcmin, dhmin
  INTRINSIC TRIM
  INTRINSIC MIN
  INTRINSIC MAX
  INTEGER :: branch
  INTEGER :: ad_to
  INTEGER :: ad_to0
  INTEGER :: ad_to1
  INTEGER :: ad_to2
  INTEGER :: ad_to3
  INTEGER :: ad_to4
  INTEGER :: ad_to5
  INTEGER :: ad_to6
  INTEGER :: ad_to7
  INTEGER :: ad_to8
! Set counters to zero
! Set overall min/max to boundaries of the domain of validity
  dcmax = cmax
  dcmin = cmin
! Check pres
  DO k=1,k0
    DO j=1,j0
      DO i=1,i0
        IF (pres(i, j, k, ismpl) .LT. pmin) THEN
! Change pres value to minimum of the domain of validity
          pres(i, j, k, ismpl) = pmin
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (pres(i, j, k, ismpl) .GT. pmax) THEN
! Change pres value to maximum of the domain of validity
          pres(i, j, k, ismpl) = pmax
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
      END DO
      CALL PUSHINTEGER8(i - 1)
    END DO
    CALL PUSHINTEGER8(j - 1)
  END DO
  CALL PUSHINTEGER8(k - 1)
! Check temp
  DO k=1,k0
    DO j=1,j0
      DO i=1,i0
        IF (temp(i, j, k, ismpl) .LT. tmin) THEN
          CALL PUSHREAL8(temp(i, j, k, ismpl))
          temp(i, j, k, ismpl) = tmin
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (temp(i, j, k, ismpl) .GT. tmax) THEN
          CALL PUSHREAL8(temp(i, j, k, ismpl))
          temp(i, j, k, ismpl) = tmax
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
      END DO
      CALL PUSHINTEGER8(i - 1)
    END DO
    CALL PUSHINTEGER8(j - 1)
  END DO
  CALL PUSHINTEGER8(k - 1)
! Check conc
  DO k=1,k0
    DO j=1,j0
      DO i=1,i0
        DO l=1,ntrac
          IF (conc(i, j, k, l, ismpl) .GT. cmax) THEN
            IF (dcmax .LT. conc(i, j, k, l, ismpl)) THEN
              dcmax = conc(i, j, k, l, ismpl)
            ELSE
              dcmax = dcmax
            END IF
            CALL PUSHREAL8(conc(i, j, k, l, ismpl))
            conc(i, j, k, l, ismpl) = cmax
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          IF (conc(i, j, k, l, ismpl) .LT. cmin .AND. conc(i, j, k, l, &
&             ismpl) .LT. -csmin) THEN
            IF (dcmin .GT. conc(i, j, k, l, ismpl)) THEN
              dcmin = conc(i, j, k, l, ismpl)
            ELSE
              dcmin = dcmin
            END IF
            CALL PUSHREAL8(conc(i, j, k, l, ismpl))
            conc(i, j, k, l, ismpl) = cmin
            CALL PUSHCONTROL1B(0)
          ELSE
            CALL PUSHCONTROL1B(1)
          END IF
          IF (conc(i, j, k, l, ismpl) .LT. csmin) THEN
! very small conc values set to zero to avoid
! numerically instabilities
            CALL PUSHREAL8(conc(i, j, k, l, ismpl))
            conc(i, j, k, l, ismpl) = cmin
            CALL PUSHCONTROL1B(1)
          ELSE
            CALL PUSHCONTROL1B(0)
          END IF
        END DO
        CALL PUSHINTEGER8(l - 1)
      END DO
      CALL PUSHINTEGER8(i - 1)
    END DO
    CALL PUSHINTEGER8(j - 1)
  END DO
  CALL PUSHINTEGER8(k - 1)
!       disable the warning output for linfos(3)==-1
  IF (linfos(3) .GE. 0) THEN
! error outputs for hard physical concentration boundaries
    IF (dcmax .GT. cmax) THEN
      STOP
    ELSE IF (dcmin .GT. cmin) THEN
      STOP
    END IF
  END IF
  CALL POPINTEGER8(ad_to8)
  DO k=ad_to8,1,-1
    CALL POPINTEGER8(ad_to7)
    DO j=ad_to7,1,-1
      CALL POPINTEGER8(ad_to6)
      DO i=ad_to6,1,-1
        CALL POPINTEGER8(ad_to5)
        DO l=ad_to5,1,-1
          CALL POPCONTROL1B(branch)
          IF (branch .NE. 0) THEN
            CALL POPREAL8(conc(i, j, k, l, ismpl))
            conc_ad(i, j, k, l, ismpl) = 0.D0
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(conc(i, j, k, l, ismpl))
            conc_ad(i, j, k, l, ismpl) = 0.D0
          END IF
          CALL POPCONTROL1B(branch)
          IF (branch .EQ. 0) THEN
            CALL POPREAL8(conc(i, j, k, l, ismpl))
            conc_ad(i, j, k, l, ismpl) = 0.D0
          END IF
        END DO
      END DO
    END DO
  END DO
  CALL POPINTEGER8(ad_to4)
  DO k=ad_to4,1,-1
    CALL POPINTEGER8(ad_to3)
    DO j=ad_to3,1,-1
      CALL POPINTEGER8(ad_to2)
      DO i=ad_to2,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          CALL POPREAL8(temp(i, j, k, ismpl))
          temp_ad(i, j, k, ismpl) = 0.D0
        END IF
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          CALL POPREAL8(temp(i, j, k, ismpl))
          temp_ad(i, j, k, ismpl) = 0.D0
        END IF
      END DO
    END DO
  END DO
  CALL POPINTEGER8(ad_to1)
  DO k=ad_to1,1,-1
    CALL POPINTEGER8(ad_to0)
    DO j=ad_to0,1,-1
      CALL POPINTEGER8(ad_to)
      DO i=ad_to,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) pres_ad(i, j, k, ismpl) = 0.D0
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) pres_ad(i, j, k, ismpl) = 0.D0
      END DO
    END DO
  END DO
END SUBROUTINE CHECK_DOMAIN_AD

