!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of lk in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *propunit *tsal lk
!   with respect to varying inputs: *temp *propunit *tsal
!   Plus diff mem management of: temp:in propunit:in tsal:in pres:in
!>    @brief average thermal conductivities on cell faces in z direction
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return z thermal conductivity (J/mK,ismpl)
SUBROUTINE LK_AD(i, j, k, ismpl, lk_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_TEMP
  IMPLICIT NONE
  double precision :: lk_adv
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL LZ
  EXTERNAL LZ_AD
  DOUBLE PRECISION :: f1, f2, prod, summ, LZ
  DOUBLE PRECISION :: f1_ad, f2_ad, prod_ad, summ_ad
  INTEGER :: arg1
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: lk
  IF (k0 .GT. 1 .AND. k .LT. k0) THEN
    f1 = LZ(i, j, k, ismpl)
    arg1 = k + 1
    f2 = LZ(i, j, arg1, ismpl)
    prod = f1*f2
    summ = f1*delz(k+1) + f2*delz(k)
    IF (summ .GT. 0.d0) THEN
      temporary_ad = 2.d0*lk_adv/summ
      prod_ad = temporary_ad
      summ_ad = -(prod*temporary_ad/summ)
    ELSE
      prod_ad = 0.D0
      summ_ad = 0.D0
    END IF
    f1_ad = delz(k+1)*summ_ad + f2*prod_ad
    f2_ad = delz(k)*summ_ad + f1*prod_ad
    CALL LZ_AD(i, j, arg1, ismpl, f2_ad)
    CALL LZ_AD(i, j, k, ismpl, f1_ad)
  END IF
END SUBROUTINE LK_AD

