!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of stab_param in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: value
!   with respect to varying inputs: value
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief stabilise paramter (cutting to its limits)
!>    @param[in] value paramter value
!>    @param[in] s_k component index (parameter type)
!>    @param[in] s_u unit index
SUBROUTINE STAB_PARAM_AD(value, value_ad, s_k, s_u)
  use arrays

  USE ARRAYS_AD

  IMPLICIT NONE
  DOUBLE PRECISION :: value
  DOUBLE PRECISION :: value_ad
  INTEGER :: s_k, s_u
  INTEGER :: branch
!
  IF (s_k .GT. nprop_load) THEN
    STOP
  ELSE IF (s_u .GT. nunits) THEN
    STOP
  ELSE
    IF (value .GT. prop_max(s_k)) THEN
      value = prop_max(s_k)
      CALL PUSHCONTROL1B(0)
    ELSE
      CALL PUSHCONTROL1B(1)
    END IF
    IF (value .LT. prop_min(s_k)) value_ad = 0.D0
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) value_ad = 0.D0
  END IF
END SUBROUTINE STAB_PARAM_AD

