!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of vx in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *head *propunit *tsal
!                *pres vx
!   with respect to varying inputs: *temp *head *propunit *tsal
!                *pres
!   Plus diff mem management of: temp:in head:in propunit:in tsal:in
!                pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief calculate velocities at cell  faces
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return x velocity (m/s)
SUBROUTINE VX_AD(i, j, k, ismpl, vx_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  IMPLICIT NONE
  double precision :: vx_adv
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL TI
  EXTERNAL TI_AD
  DOUBLE PRECISION :: dif, TI
  DOUBLE PRECISION :: dif_ad
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1_ad
  DOUBLE PRECISION :: vx
  IF (i0 .GT. 1 .AND. i .LT. i0 .AND. head_active) THEN
    dif = head(i+1, j, k, ismpl) - head(i, j, k, ismpl)
    result1 = TI(i, j, k, ismpl)
    result1_ad = -(dif*vx_adv)
    dif_ad = -(result1*vx_adv)
    CALL TI_AD(i, j, k, ismpl, result1_ad)
    head_ad(i+1, j, k, ismpl) = head_ad(i+1, j, k, ismpl) + dif_ad
    head_ad(i, j, k, ismpl) = head_ad(i, j, k, ismpl) - dif_ad
  END IF
END SUBROUTINE VX_AD

