!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of vy in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *head *propunit *tsal
!                *pres vy
!   with respect to varying inputs: *temp *head *propunit *tsal
!                *pres
!   Plus diff mem management of: temp:in head:in propunit:in tsal:in
!                pres:in
!>    @brief calculate velocities at cell  faces
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return y velocity (m/s)
SUBROUTINE VY_AD(i, j, k, ismpl, vy_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  IMPLICIT NONE
  double precision :: vy_adv
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL TJ
  EXTERNAL TJ_AD
  DOUBLE PRECISION :: dif, TJ
  DOUBLE PRECISION :: dif_ad
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1_ad
  DOUBLE PRECISION :: vy
  IF (j0 .GT. 1 .AND. j .LT. j0 .AND. head_active) THEN
    dif = head(i, j+1, k, ismpl) - head(i, j, k, ismpl)
    result1 = TJ(i, j, k, ismpl)
    result1_ad = -(dif*vy_adv)
    dif_ad = -(result1*vy_adv)
    CALL TJ_AD(i, j, k, ismpl, result1_ad)
    head_ad(i, j+1, k, ismpl) = head_ad(i, j+1, k, ismpl) + dif_ad
    head_ad(i, j, k, ismpl) = head_ad(i, j, k, ismpl) - dif_ad
  END IF
END SUBROUTINE VY_AD

