!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of di in forward (tangent) mode:
!   variations   of useful results: di
!   with respect to varying inputs: *temp *head *propunit *tsal
!                *pres
!   Plus diff mem management of: temp:in head:in propunit:in tsal:in
!                pres:in
!>    @brief average effective diffusivities on cell faces in x direction
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] spec species
!>    @param[in] ismpl local sample index
!>    @return effective diffusivities (J/mK)
DOUBLE PRECISION FUNCTION g_DI(i, j, k, spec, ismpl, di)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  INTEGER :: spec
  DOUBLE PRECISION :: f1, f2, prod, summ, betx, bety, betz, bet
  DOUBLE PRECISION :: g_f1, g_f2, g_prod, g_summ, g_betx, &
& g_bety, g_betz, g_bet
  EXTERNAL POR, DISP, VX, VY, VZ
  EXTERNAL g_POR, g_DISP, g_VX, g_VY, g_VZ
  DOUBLE PRECISION :: POR, DISP, VX, VY, &
& VZ
  DOUBLE PRECISION :: g_POR, g_DISP, g_VX, g_VY, g_VZ
  INTRINSIC SQRT
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: result2
  DOUBLE PRECISION :: g_result2
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: di
  di = 0.d0
  betx = 0.d0
  bety = 0.d0
  betz = 0.d0
  IF (k0 .GT. 1 .AND. k .LT. k0) THEN
    g_betz = g_VZ(i, j, k, ismpl, betz)
    g_betz = 2*betz*g_betz
    betz = betz*betz
  ELSE
    g_betz = 0.D0
  END IF
  IF (j0 .GT. 1 .AND. j .LT. j0) THEN
    g_bety = g_VY(i, j, k, ismpl, bety)
    g_bety = 2*bety*g_bety
    bety = bety*bety
  ELSE
    g_bety = 0.D0
  END IF
  IF (i0 .GT. 1 .AND. i .LT. i0) THEN
    g_betx = g_VX(i, j, k, ismpl, betx)
    g_betx = 2*betx*g_betx
    betx = betx*betx
    temp0 = SQRT(betx + bety + betz)
    IF (betx + bety + betz .EQ. 0.0) THEN
      g_bet = 0.D0
    ELSE
      g_bet = (g_betx+g_bety+g_betz)/(2.0*temp0)
    END IF
    bet = temp0
    g_result1 = g_POR(i, j, k, ismpl, result1)
    g_result2 = g_DISP(i, j, k, ismpl, result2)
    g_f1 = diff_c(spec)*g_result1 + bet*g_result2 + result2*&
&     g_bet
    f1 = result1*diff_c(spec) + result2*bet
    g_result1 = g_POR(i + 1, j, k, ismpl, result1)
    g_result2 = g_DISP(i + 1, j, k, ismpl, result2)
    g_f2 = diff_c(spec)*g_result1 + bet*g_result2 + result2*&
&     g_bet
    f2 = result1*diff_c(spec) + result2*bet
    g_prod = f2*g_f1 + f1*g_f2
    prod = f1*f2
    g_summ = delx(i+1)*g_f1 + delx(i)*g_f2
    summ = f1*delx(i+1) + f2*delx(i)
    IF (summ .GT. 0.d0) THEN
      g_di = 2.d0*(g_prod-prod*g_summ/summ)/summ
      di = 2.d0*prod/summ
    ELSE
      g_di = 0.D0
    END IF
  ELSE
    g_di = 0.D0
  END IF
  RETURN
END FUNCTION g_DI

