!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of lk in forward (tangent) mode:
!   variations   of useful results: lk
!   with respect to varying inputs: *temp *propunit *tsal
!   Plus diff mem management of: temp:in propunit:in tsal:in pres:in
!>    @brief average thermal conductivities on cell faces in z direction
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return z thermal conductivity (J/mK,ismpl)
DOUBLE PRECISION FUNCTION g_LK(i, j, k, ismpl, lk)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  USE MOD_TEMP
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL LZ
  EXTERNAL g_LZ
  DOUBLE PRECISION :: f1, f2, prod, summ, LZ
  DOUBLE PRECISION :: g_f1, g_f2, g_prod, g_summ, g_LZ
  DOUBLE PRECISION :: lk
  lk = 0.d0
  IF (k0 .GT. 1 .AND. k .LT. k0) THEN
    g_f1 = g_LZ(i, j, k, ismpl, f1)
    g_f2 = g_LZ(i, j, k + 1, ismpl, f2)
    g_prod = f2*g_f1 + f1*g_f2
    prod = f1*f2
    g_summ = delz(k+1)*g_f1 + delz(k)*g_f2
    summ = f1*delz(k+1) + f2*delz(k)
    IF (summ .GT. 0.d0) THEN
      g_lk = 2.d0*(g_prod-prod*g_summ/summ)/summ
      lk = 2.d0*prod/summ
    ELSE
      g_lk = 0.D0
    END IF
  ELSE
    g_lk = 0.D0
  END IF
  RETURN
END FUNCTION g_LK

