!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of vx in forward (tangent) mode:
!   variations   of useful results: vx
!   with respect to varying inputs: *temp *head *propunit *tsal
!                *pres
!   Plus diff mem management of: temp:in head:in propunit:in tsal:in
!                pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief calculate velocities at cell  faces
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return x velocity (m/s)
DOUBLE PRECISION FUNCTION g_VX(i, j, k, ismpl, vx)
  USE ARRAYS

  USE g_ARRAYS

  USE MOD_GENRL
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL TI
  EXTERNAL g_TI
  DOUBLE PRECISION :: dif, TI
  DOUBLE PRECISION :: g_dif, g_TI
  EXTERNAL DUMMY
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: g_result1
  DOUBLE PRECISION :: vx
  vx = 0.d0
  IF (.NOT.head_active .AND. vdefaultswitch) vx = vdefault(1, ismpl)
  IF (i0 .GT. 1 .AND. i .LT. i0 .AND. head_active) THEN
#ifdef head_base
    g_dif = g_head(i+1, j, k, ismpl) - g_head(i, j, k, ismpl)
    dif = head(i+1, j, k, ismpl) - head(i, j, k, ismpl)
    g_result1 = g_TI(i, j, k, ismpl, result1)
    g_vx = -(dif*g_result1+result1*g_dif)
    vx = -(result1*dif)
#endif
  ELSE
    g_vx = 0.D0
  END IF
  RETURN
END FUNCTION g_VX

