!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of qt in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *propunit qt
!   with respect to varying inputs: *propunit
!   Plus diff mem management of: propunit:in simtime:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief assign heat production to cell
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return heat production
SUBROUTINE QT_AD(i, j, k, ismpl, qt_adv)
  USE WORK_ARRAY_GHE
  use arrays

  USE ARRAYS_AD

  IMPLICIT NONE
  double precision :: qt_adv
!       USE mod_genrl
!       USE mod_genrlc
!        IMPLICIT NONE
  INTEGER :: i, j, k, ismpl
  INTEGER :: branch
  DOUBLE PRECISION :: qt
!       DOUBLE PRECISION por
! vr : aCtor (1-por) ?
!      por=propunit(uindex(i,j,k),idx_por,ismpl)
!      qt = (1.d0- por)*(propunit(uindex(i,j,k),idx_q,ismpl)
  IF (simtime(ismpl) .LE. tin(mp, 1)) THEN
    mp = mp
  ELSE
    mp = mp + 1
  END IF
!        WRITE(*,*),Tin(m,1)
!       Anfang Schleife über Sonden
  DO nl=1,nghe
    IF (tin(mp, 2) .NE. 0) THEN
!  An/aus
!            DO kl=k_start(nl),k_end(nl)
      IF (i .EQ. ighe(nl) .AND. j .EQ. jghe(nl) .AND. (k .GE. k_start(nl&
&         ) .AND. k .LE. k_end(nl))) THEN
        CALL PUSHCONTROL2B(2)
      ELSE
        CALL PUSHCONTROL2B(1)
      END IF
    ELSE
      CALL PUSHCONTROL2B(0)
    END IF
  END DO
  DO nl=nghe,1,-1
    CALL POPCONTROL2B(branch)
    IF (branch .EQ. 0) THEN
      propunit_ad(uindex(i, j, k), idx_q, ismpl) = propunit_ad(uindex(i&
&       , j, k), idx_q, ismpl) + qt_adv
      qt_adv = 0.D0
    ELSE IF (branch .NE. 1) THEN
      qt_adv = 0.D0
    END IF
  END DO
  propunit_ad(uindex(i, j, k), idx_q, ismpl) = propunit_ad(uindex(i, j, &
&   k), idx_q, ismpl) + qt_adv
END SUBROUTINE QT_AD

