!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of alfa in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: alfa
!   with respect to varying inputs: x
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief truncated series expansion of cosh(x) for x < 0.1
!>    @param[in] x input value
!>    @return truncated function value
SUBROUTINE ALFA_AD(x, x_ad, alfa_adv)
  IMPLICIT NONE
  double precision :: alfa_adv
  DOUBLE PRECISION :: x
  DOUBLE PRECISION :: x_ad
  INTRINSIC ABS
  INTRINSIC TANH
  DOUBLE PRECISION :: abs0
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: temp
  DOUBLE PRECISION :: alfa
!      double precision x2, x3, x5, x7
  IF (x .GE. 0.) THEN
    abs0 = x
  ELSE
    abs0 = -x
  END IF
  IF (abs0 .GT. 1.d-30) THEN
    temp = TANH(x)
    temporary_ad = alfa_adv/x
    x_ad = (1.0/temp-(1.0-TANH(x)**2)*x/temp**2-(x/temp-1.d0)/x)*temporary_ad
  ELSE
    x_ad = 0.D0
  END IF
END SUBROUTINE ALFA_AD

