!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of lj in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *propunit *tsal lj
!   with respect to varying inputs: *temp *propunit *tsal
!   Plus diff mem management of: temp:in propunit:in tsal:in pres:in
!>    @brief average thermal conductivities on cell faces in y direction
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return y thermal conductivity (J/mK)
SUBROUTINE LJ_AD(i, j, k, ismpl, lj_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_TEMP
  IMPLICIT NONE
  double precision :: lj_adv
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL LY
  EXTERNAL LY_AD
  DOUBLE PRECISION :: f1, f2, prod, summ, LY
  DOUBLE PRECISION :: f1_ad, f2_ad, prod_ad, summ_ad
  INTEGER :: arg1
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: lj
  IF (j0 .GT. 1 .AND. j .LT. j0) THEN
    f1 = LY(i, j, k, ismpl)
    arg1 = j + 1
    f2 = LY(i, arg1, k, ismpl)
    prod = f1*f2
    summ = f1*dely(j+1) + f2*dely(j)
    IF (summ .GT. 0.d0) THEN
      temporary_ad = 2.d0*lj_adv/summ
      prod_ad = temporary_ad
      summ_ad = -(prod*temporary_ad/summ)
    ELSE
      prod_ad = 0.D0
      summ_ad = 0.D0
    END IF
    f1_ad = dely(j+1)*summ_ad + f2*prod_ad
    f2_ad = dely(j)*summ_ad + f1*prod_ad
    CALL LY_AD(i, arg1, k, ismpl, f2_ad)
    CALL LY_AD(i, j, k, ismpl, f1_ad)
  END IF
END SUBROUTINE LJ_AD

