!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of pres2head in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: (global)*temp[_:_,_:_,_:_,_:_]
!                (global)*head[_:_,_:_,_:_,_:_] (global)*dbc_data[_:_,_:_,_:_]
!                (global)*bcperiod[_:_,_:_,_:_,_:_] (global)*propunit[_:_,_:_,_:_]
!                (global)*pres[_:_,_:_,_:_,_:_]
!   with respect to varying inputs: (global)*temp[_:_,_:_,_:_,_:_]
!                (global)*head[_:_,_:_,_:_,_:_] (global)*dbc_data[_:_,_:_,_:_]
!                (global)*bcperiod[_:_,_:_,_:_,_:_] (global)*propunit[_:_,_:_,_:_]
!                (global)*pres[_:_,_:_,_:_,_:_]
!   Plus diff mem management of: (global)temp:in (global)head:in
!                (global)dbc_data:in (global)bcperiod:in (global)propunit:in
!                (global)pres:in (global)simtime:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief compute hydraulic head from pressure
!>    @param[in] init flag: 0-init, 1-normal setup
!>    @param[in] ismpl local sample index
!>    @details
!>    parallelisation wrapper for hydraulic head computation
SUBROUTINE PRES2HEAD_AD(init, ismpl)
  USE MOD_LINFOS
  USE MOD_OMP_TOOLS
  IMPLICIT NONE
  INTEGER :: ismpl
  INCLUDE 'OMP_TOOLS.inc'
  INTEGER :: init
  CALL OMP_PRES2HEAD_AD(init, ismpl)
END SUBROUTINE PRES2HEAD_AD

