!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of set_pbc in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *d *e *f *g *w *dbc_data *bcperiod
!                *propunit *pres *a *b *c
!   with respect to varying inputs: *d *e *f *g *w *dbc_data *bcperiod
!                *propunit *pres *a *b *c
!   Plus diff mem management of: d:in e:in f:in g:in w:in dbc_data:in
!                bcperiod:in propunit:in pres:in simtime:in a:in
!                b:in c:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief modify coefficents for the head equation according to the boundary
!>    @param[in] ismpl local sample index
!>    @details
!> modify coefficents for the head equation according to the boundary conditions\n
!> coefficients are stored as vectors in the diagonals a-g (d center) and rhs in w.\n
SUBROUTINE SET_PBC_AD(ismpl)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_GENRLC
  USE MOD_TEMP
  USE MOD_FLOW
  use mod_time

  USE MOD_TIME_AD

  USE MOD_LINFOS
  IMPLICIT NONE
  INTEGER :: ismpl
  INTEGER :: i, j, k
  INTEGER :: ib
  INTEGER :: bcu, tpbcu, bctype, i_dir
  DOUBLE PRECISION :: val, malfa, mbeta
  DOUBLE PRECISION :: val_ad, malfa_ad, mbeta_ad
  INTRINSIC MAX
  INTEGER :: branch
  INTEGER :: ad_from
  INTEGER :: ad_to
  INTEGER :: ad_count
  INTEGER :: i1
  ad_from = first_flow
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! dirichlet nodes - - - - - - - - - - - - - - - - - - - - - - - - - - -
  DO ib=ad_from,last_flow
    i = ibc_data(ib, cbc_i)
    j = ibc_data(ib, cbc_j)
    k = ibc_data(ib, cbc_k)
    bcu = ibc_data(ib, cbc_bcu)
    IF (ibc_data(ib, cbc_bctp) .LT. 0) THEN
      tpbcu = 0
    ELSE
      tpbcu = ibc_data(ib, cbc_bctp)
    END IF
    bctype = ibc_data(ib, cbc_bt)
!aw      i_dir = ibc_data(ib,cbc_dir)
!        "dirichlet"?, skip otherwise
    IF (bctype .EQ. bt_diri) THEN
!           discrete values
      IF (bcu .LE. 0) THEN
        CALL PUSHREAL8(val)
        val = dbc_data(ib, 1, ismpl)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8(val)
        val = propunit(bcu, idx_hbc, ismpl)
        CALL PUSHCONTROL1B(1)
      END IF
      IF (tpbcu .GT. 0 .AND. nbctp .GT. 0) THEN
!               time-dependent bc:  val=ac*val+bc
!               get Alfa and Beta modificators
        CALL PUSHINTEGER8(tpbcu)
        CALL PUSHREAL8(mbeta)
        CALL GET_TPBCALBE(malfa, mbeta, tpbcu, ismpl)
!               update time dependend modification of the bc-value
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (tpbcu .GE. 0) THEN
        CALL PUSHCONTROL2B(2)
      ELSE
        CALL PUSHCONTROL2B(1)
      END IF
    ELSE
      CALL PUSHCONTROL2B(0)
    END IF
  END DO
  CALL PUSHINTEGER8(ib - 1)
  CALL PUSHINTEGER8(ad_from)
  CALL PUSHINTEGER8(ib)
  ad_count = 1
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! neumann  nodes    - - - - - - - - - - - - - - - - - - - - - - - - - -
  DO ib=first_flow,last_flow
    CALL PUSHINTEGER8(i)
    i = ibc_data(ib, cbc_i)
    CALL PUSHINTEGER8(j)
    j = ibc_data(ib, cbc_j)
    CALL PUSHINTEGER8(k)
    k = ibc_data(ib, cbc_k)
    bcu = ibc_data(ib, cbc_bcu)
    IF (ibc_data(ib, cbc_bctp) .LT. 0) THEN
      tpbcu = 0
    ELSE
      tpbcu = ibc_data(ib, cbc_bctp)
    END IF
    bctype = ibc_data(ib, cbc_bt)
    i_dir = ibc_data(ib, cbc_dir)
!        "neumann"?, skip otherwise
    IF (bctype .EQ. bt_neum) THEN
!           discrete values
      IF (bcu .LE. 0) THEN
        CALL PUSHREAL8(val)
        val = dbc_data(ib, 1, ismpl)
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHREAL8(val)
        val = propunit(bcu, idx_hbc, ismpl)
        CALL PUSHCONTROL1B(1)
      END IF
!
      IF (tpbcu .GT. 0 .AND. nbctp .GT. 0) THEN
!               time-dependent bc:  val=ac*val+bc
!               get Alfa and Beta modificators
        CALL PUSHINTEGER8(tpbcu)
        CALL PUSHREAL8(mbeta)
        CALL GET_TPBCALBE(malfa, mbeta, tpbcu, ismpl)
!               update time dependend modification of the bc-value
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (tpbcu .GE. 0) THEN
        IF (i_dir .EQ. 0) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (i_dir .EQ. 1 .OR. i_dir .EQ. 2) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (i_dir .EQ. 3 .OR. i_dir .EQ. 4) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        IF (i_dir .EQ. 5 .OR. i_dir .EQ. 6) THEN
          CALL PUSHCONTROL1B(0)
        ELSE
          CALL PUSHCONTROL1B(1)
        END IF
        CALL PUSHCONTROL2B(0)
      ELSE
        CALL PUSHCONTROL2B(1)
      END IF
    ELSE
      CALL PUSHCONTROL2B(2)
    END IF
!          WELLMODEL  
    IF (bctype .EQ. bt_neuw) THEN
!           discrete values
      CALL PUSHREAL8(val)
      val = dbc_data(ib, 1, ismpl)
!
      IF (tpbcu .GT. 0 .AND. nbctp .GT. 0) THEN
!               time-dependent bc:  val=ac*val+bc
!               get Alfa and Beta modificators
        CALL PUSHINTEGER8(tpbcu)
        CALL PUSHREAL8(mbeta)
        CALL GET_TPBCALBE(malfa, mbeta, tpbcu, ismpl)
!               update time dependend modification of the bc-value
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      IF (tpbcu .GE. 0) THEN
        IF (i_dir .NE. 0) THEN
          GOTO 130
        ELSE
          CALL PUSHCONTROL2B(2)
        END IF
      ELSE
        CALL PUSHCONTROL2B(1)
      END IF
    ELSE
      CALL PUSHCONTROL2B(0)
    END IF
    CALL PUSHINTEGER8(ib)
    ad_count = ad_count + 1
  END DO
  CALL PUSHCONTROL1B(0)
  CALL PUSHINTEGER8(ad_count)
  CALL POPINTEGER8(ad_count)
  DO i1=1,ad_count
    IF (i1 .EQ. 1) THEN
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        GOTO 120
      ELSE
        IF (ALLOCATED(d_ad)) d_ad = 0.D0
        IF (ALLOCATED(e_ad)) e_ad = 0.D0
        IF (ALLOCATED(f_ad)) f_ad = 0.D0
        IF (ALLOCATED(g_ad)) g_ad = 0.D0
        IF (ALLOCATED(w_ad)) w_ad = 0.D0
        IF (ALLOCATED(dbc_data_ad)) dbc_data_ad = 0.D0
        IF (ALLOCATED(bcperiod_ad)) bcperiod_ad = 0.D0
        IF (ALLOCATED(propunit_ad)) propunit_ad = 0.D0
        IF (ALLOCATED(pres_ad)) pres_ad = 0.D0
        IF (ALLOCATED(a_ad)) a_ad = 0.D0
        IF (ALLOCATED(b_ad)) b_ad = 0.D0
        IF (ALLOCATED(c_ad)) c_ad = 0.D0
        val_ad = 0.D0
      END IF
    ELSE
      CALL POPCONTROL2B(branch)
      IF (branch .EQ. 0) THEN
        GOTO 100
      ELSE IF (branch .EQ. 1) THEN
        val_ad = 0.D0
      ELSE
        i = ibc_data(ib, cbc_i)
        j = ibc_data(ib, cbc_j)
        k = ibc_data(ib, cbc_k)
        val_ad = -w_ad(i, j, k, ismpl)
        val_ad = val_ad/(delx(i)*dely(j)*delz(k))
      END IF
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      malfa_ad = val_ad
      mbeta_ad = val*val_ad
      val_ad = mbeta*val_ad
      CALL POPREAL8(mbeta)
      CALL POPINTEGER8(tpbcu)
      CALL GET_TPBCALBE_AD(malfa, malfa_ad, mbeta, mbeta_ad, tpbcu, &
&                    ismpl)
    END IF
    CALL POPREAL8(val)
    dbc_data_ad(ib, 1, ismpl) = dbc_data_ad(ib, 1, ismpl) + val_ad
 100 CALL POPCONTROL2B(branch)
    IF (branch .EQ. 0) THEN
      val_ad = -w_ad(i, j, k, ismpl)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) val_ad = val_ad/delz(k)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) val_ad = val_ad/dely(j)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) val_ad = val_ad/delx(i)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) val_ad = val_ad/(delx(i)*dely(j)*delz(k))
    ELSE IF (branch .EQ. 1) THEN
      val_ad = 0.D0
    ELSE
      GOTO 110
    END IF
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      malfa_ad = val_ad
      mbeta_ad = val*val_ad
      val_ad = mbeta*val_ad
      CALL POPREAL8(mbeta)
      CALL POPINTEGER8(tpbcu)
      CALL GET_TPBCALBE_AD(malfa, malfa_ad, mbeta, mbeta_ad, tpbcu, &
&                    ismpl)
    END IF
    bcu = ibc_data(ib, cbc_bcu)
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      CALL POPREAL8(val)
      dbc_data_ad(ib, 1, ismpl) = dbc_data_ad(ib, 1, ismpl) + val_ad
    ELSE
      CALL POPREAL8(val)
      propunit_ad(bcu, idx_hbc, ismpl) = propunit_ad(bcu, idx_hbc, ismpl&
&       ) + val_ad
    END IF
 110 CALL POPINTEGER8(k)
    CALL POPINTEGER8(j)
    CALL POPINTEGER8(i)
 120 CALL POPINTEGER8(ib)
  END DO
  CALL POPINTEGER8(ad_from)
  CALL POPINTEGER8(ad_to)
  DO ib=ad_to,ad_from,-1
    CALL POPCONTROL2B(branch)
    IF (branch .NE. 0) THEN
      IF (branch .EQ. 1) THEN
        val_ad = 0.D0
      ELSE
        i = ibc_data(ib, cbc_i)
        j = ibc_data(ib, cbc_j)
        k = ibc_data(ib, cbc_k)
        val_ad = pres_ad(i, j, k, ismpl) + w_ad(i, j, k, ismpl)
        pres_ad(i, j, k, ismpl) = 0.D0
        w_ad(i, j, k, ismpl) = 0.D0
        d_ad(i, j, k, ismpl) = 0.D0
        g_ad(i, j, k, ismpl) = 0.D0
        f_ad(i, j, k, ismpl) = 0.D0
        e_ad(i, j, k, ismpl) = 0.D0
        c_ad(i, j, k, ismpl) = 0.D0
        b_ad(i, j, k, ismpl) = 0.D0
        a_ad(i, j, k, ismpl) = 0.D0
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        malfa_ad = val_ad
        mbeta_ad = val*val_ad
        val_ad = mbeta*val_ad
        CALL POPREAL8(mbeta)
        CALL POPINTEGER8(tpbcu)
        CALL GET_TPBCALBE_AD(malfa, malfa_ad, mbeta, mbeta_ad, tpbcu, &
&                      ismpl)
      END IF
      bcu = ibc_data(ib, cbc_bcu)
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        CALL POPREAL8(val)
        dbc_data_ad(ib, 1, ismpl) = dbc_data_ad(ib, 1, ismpl) + val_ad
      ELSE
        CALL POPREAL8(val)
        propunit_ad(bcu, idx_hbc, ismpl) = propunit_ad(bcu, idx_hbc, &
&         ismpl) + val_ad
      END IF
    END IF
  END DO
  GOTO 140
 130 CALL PUSHCONTROL1B(1)
  CALL PUSHINTEGER8(ad_count)
  STOP
 140 CONTINUE
END SUBROUTINE SET_PBC_AD

