!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of vy in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *propunit *tsal *pres
!                vy
!   with respect to varying inputs: *temp *propunit *tsal *pres
!   Plus diff mem management of: temp:in propunit:in tsal:in pres:in
!>    @brief calculate velocities at cell faces
!>    @param[in] i grid indices
!>    @param[in] j grid indices
!>    @param[in] k grid indices
!>    @param[in] ismpl local sample index
!>    @return y velocity (m/(Pa s))
SUBROUTINE VY_AD(i, j, k, ismpl, vy_adv)
  use arrays

  USE ARRAYS_AD

  USE MOD_GENRL
  USE MOD_FLOW
  IMPLICIT NONE
  double precision :: vy_adv
  INTEGER :: ismpl
  INTEGER :: i, j, k
  EXTERNAL GJ
  EXTERNAL GJ_AD0
  DOUBLE PRECISION :: f1, f2, dif, GJ
  DOUBLE PRECISION :: dif_ad
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1_ad
  DOUBLE PRECISION :: vy
  IF (j0 .GT. 1 .AND. j .LT. j0) THEN
    dif = pres(i, j+1, k, ismpl) - pres(i, j, k, ismpl)
    result1 = GJ(i, j, k, ismpl)
    result1_ad = -(dif*vy_adv)
    dif_ad = -(result1*vy_adv)
    CALL GJ_AD0(i, j, k, ismpl, result1_ad)
    pres_ad(i, j+1, k, ismpl) = pres_ad(i, j+1, k, ismpl) + dif_ad
    pres_ad(i, j, k, ismpl) = pres_ad(i, j, k, ismpl) - dif_ad
  END IF
END SUBROUTINE VY_AD

