!        Generated by TAPENADE     (INRIA, Tropics team)
!  tapenade 3.x
!
!>    @brief global variables for the specification of the data
MODULE MOD_DATA_AD
  IMPLICIT NONE
!             all,  temp.,  head.,  conc.,  epot.,  pres.,  ???,    sat_n
!  INTEGER :: ndata, ndata_t, ndata_h, ndata_c, ndata_e, ndata_p, ndata_b&
!&  , ndata_s
END MODULE MOD_DATA_AD
