!        Generated by TAPENADE     (INRIA, Tropics team)
!  tapenade 3.x
!
!>    @brief commonly used global variables and constants
MODULE MOD_GENRL_AD
  IMPLICIT NONE
  DOUBLE PRECISION :: tslocal
!
!     memory of data in 8Bytes (std. double precision size)
!  DOUBLE PRECISION :: memory
!     file output compression tool
!  INTEGER :: compress_out
!  INTEGER :: i0, j0, k0
!  INTEGER :: out_orientation
!  INTEGER :: runmode
!  INTEGER :: maxiter_nl
!  INTEGER :: nladapt
!
!  LOGICAL :: head_active, temp_active
!  LOGICAL :: trac_active, chem_active, trans_active, pres_active
!  LOGICAL :: vtk_out, tec_out, hdf_out, txt_out
!     pres/head is init an no need to compute it in "head2pres" or "pres2head" the first time
!  LOGICAL :: write_disable, write_smonitor, write_param, write_eoutt
!
! vr  change key for new parameter block
!  CHARACTER(len=1) :: key_char
!  PARAMETER (key_char='#')
!     nsmpl: number of samples
!  INTEGER :: nsmpl
!
!     useful constants
!  DOUBLE PRECISION :: two, half, big, small
!  PARAMETER (two=2.d0, half=0.5d0)
!  PARAMETER (big=1.d30, small=1.d-300)
!  DOUBLE PRECISION :: pi
!  PARAMETER (pi=3.141592653589793d0)
!
!  LOGICAL :: klogflag
!  PARAMETER (klogflag=.true.)
!
!  INTEGER :: idumfil
!  PARAMETER (idumfil=99)
!
!  INTEGER :: cgen_fw, cgen_time, cgen_fwad
!  INTEGER :: cgen_opti, cgen_dd, ncgen
!  PARAMETER (cgen_fw=1)
!       index constants for HEAD, TEMP and PRES
!       forward iteration [x_i-1,j];
!         do not change it without a change of any
!        "headold" into "headold(1,cgen_fw)" ccc
!  PARAMETER (cgen_time=2)
!       time iteration
!  PARAMETER (cgen_fwad=3)
!       nonlinear-forward iteration (use of ad)
!  PARAMETER (cgen_opti=4)
!       optimisation/realisation iteration [x_*,j]
!         index constants for g_HEAD, g_TEMP and g_PRES
!  PARAMETER (cgen_dd=5)
!       special DD use [f(x_*,j)]
!  PARAMETER (ncgen=5)
!       max number of "cgen_*"
!
!       index of the <master> sample
!  INTEGER, PARAMETER :: idx_master=1
!       Convergence flag, doubling value and doubling counter for variable time step size
!  INTEGER :: flag_delt, delt_double, delt_count, flag_1st_timestep
!       Flag for Variable step size
!  LOGICAL :: delt_vary
!       Starting, minimum, maximum, old value for delt for variable step size
!  DOUBLE PRECISION :: delt_start, delt_min, delt_max, delt_old
END MODULE MOD_GENRL_AD
