!        Generated by TAPENADE     (INRIA, Tropics team)
!  tapenade 3.x
!
!>    @brief nested OpenMP, thread level information
MODULE MOD_OMP_TOOLS_AD
  IMPLICIT NONE
!     number of threads for level 0(outer region) and 1(inner region)
  INTEGER :: tlevel_0, tlevel_1
!     nested OpenMP enabled?
  LOGICAL :: nested_build
END MODULE MOD_OMP_TOOLS_AD
