!        Generated by TAPENADE     (INRIA, Tropics team)
!  tapenade 3.x
!
!>    @brief global variables for timestepping
MODULE MOD_TIME_AD
  IMPLICIT NONE
  double precision :: thetaf_ad,thetat_ad,thetac_ad
  double precision :: max_simtime_ad
END MODULE MOD_TIME_AD
