!        Generated by TAPENADE     (INRIA, Tropics team)
!  tapenade 3.x
!
!>    @brief defines the reinjection parameters, <USER> switch
MODULE MOD_WELLS3D_AD
  IMPLICIT NONE
END MODULE MOD_WELLS3D_AD
