!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of compf in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp *pres compf
!   with respect to varying inputs: *temp *pres
!   Plus diff mem management of: temp:in pres:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!> @brief compf calculates compressibility of pure water
!> @param[in] i cell index, direction I0
!> @param[in] j cell index, direction J0
!> @param[in] k cell index, direction K0
!> @param[in] ismpl local sample index
!> @return  compressibility                     compf  [1./Pa]
!> @details
!> compf calculates compressibility of pure water \n
!> given temperature (t, in C), and pressure (p,in Pa)\n
!> at node(i,j,k).\n \n
!>
!> Method: \n
!>
!> compf = 1/rhof d/dP rhof, \n
!>
!> where rhof= water density.\n \n
!>
!> Main source of rhof (water density) approximation, see
!> props/ghe/rhof.f90. \n \n
!>
!>    range of validity:\n
!>    - pressures   0.001 - 110 MPa,\n
!>    - temperature   15 - 360 degC\n
SUBROUTINE COMPF_AD(i, j, k, ismpl, compf_adv)
  use arrays
  USE ARRAYS_AD
  USE MOD_FLOW, ONLY : pa_conv, pa_conv1
  IMPLICIT NONE
  double precision :: compf_adv
! Location indices
  INTEGER, INTENT(IN) :: i
  INTEGER, INTENT(IN) :: j
  INTEGER, INTENT(IN) :: k
! Sample index
  INTEGER :: ismpl
! Temperature (degC)
  DOUBLE PRECISION :: tlocal
  DOUBLE PRECISION :: tlocal_ad
! Pressure (MPa)
  DOUBLE PRECISION :: plocal
  DOUBLE PRECISION :: plocal_ad
! Monomials of temperature and pressure
  DOUBLE PRECISION :: t, t2, t3
  DOUBLE PRECISION :: t_ad, t2_ad, t3_ad
  DOUBLE PRECISION :: p, p2, p3, p4
  DOUBLE PRECISION :: p_ad, p2_ad, p3_ad
  DOUBLE PRECISION :: tp, t2p, tp2
  DOUBLE PRECISION :: tp_ad, t2p_ad, tp2_ad
! Coefficients of numerator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: y0=0.10000000d+01
  DOUBLE PRECISION, PARAMETER :: y1=0.17472599d-01
  DOUBLE PRECISION, PARAMETER :: y2=-0.20443098d-04
  DOUBLE PRECISION, PARAMETER :: y3=-0.17442012d-06
  DOUBLE PRECISION, PARAMETER :: y4=0.49564109d-02
  DOUBLE PRECISION, PARAMETER :: y5=-0.40757664d-04
  DOUBLE PRECISION, PARAMETER :: y6=0.50676664d-07
  DOUBLE PRECISION, PARAMETER :: y7=0.50330978d-04
  DOUBLE PRECISION, PARAMETER :: y8=0.33914814d-06
  DOUBLE PRECISION, PARAMETER :: y9=-0.18383009d-06
! Coefficients of denominator of rational function approximation
  DOUBLE PRECISION, PARAMETER :: z0=0.10009476d-02
  DOUBLE PRECISION, PARAMETER :: z1=0.16812589d-04
  DOUBLE PRECISION, PARAMETER :: z2=-0.24582622d-07
  DOUBLE PRECISION, PARAMETER :: z3=-0.17014984d-09
  DOUBLE PRECISION, PARAMETER :: z4=0.48841156d-05
  DOUBLE PRECISION, PARAMETER :: z5=-0.32967985d-07
  DOUBLE PRECISION, PARAMETER :: z6=0.28619380d-10
  DOUBLE PRECISION, PARAMETER :: z7=0.53249055d-07
  DOUBLE PRECISION, PARAMETER :: z8=0.30456698d-09
  DOUBLE PRECISION, PARAMETER :: z9=-0.12221899d-09
! Numerator and denominator of rational function approximation
  DOUBLE PRECISION :: ta, tb
  DOUBLE PRECISION :: ta_ad, tb_ad
! Derivative of numerator wrt P
  DOUBLE PRECISION :: da
  DOUBLE PRECISION :: da_ad
! Derivative of denominator wrt P
  DOUBLE PRECISION :: db
  DOUBLE PRECISION :: db_ad
! Denominator squared
  DOUBLE PRECISION :: b2
  DOUBLE PRECISION :: b2_ad
! Water density (local)
  DOUBLE PRECISION :: rhof_loc
  DOUBLE PRECISION :: rhof_loc_ad
! Derivative of water density wrt P
  DOUBLE PRECISION :: drhodp
  DOUBLE PRECISION :: drhodp_ad
! Compressibiliy in Mpa
  DOUBLE PRECISION :: compf_mpa
  DOUBLE PRECISION :: compf_mpa_ad
  DOUBLE PRECISION :: temporary_ad
  DOUBLE PRECISION :: compf
! Local Pressure in MPa
  plocal = pres(i, j, k, ismpl)*pa_conv1
! Local Temperature in degC
  tlocal = temp(i, j, k, ismpl)
! Temperature out of bounds
  IF (tlocal .GT. 360.0d0) THEN
    STOP
  ELSE IF (tlocal .LT. 0.0d0) THEN
! Relax table boundary of 15degC to error boundary 0degC
    STOP
  ELSE IF (plocal .GT. 110.0d0) THEN
! Pressure out of bounds
    STOP
  ELSE IF (plocal .LT. 0.001d0) THEN
    STOP
  ELSE
! Compute monomials in pressure and temperature
    p = plocal
    t = tlocal
    p2 = p*p
    p3 = p2*p
    t2 = t*t
    t3 = t2*t
    tp = p*t
    tp2 = t*p2
    t2p = t2*p
! Numerator of rational function approximation
    ta = y0 + y1*p + y2*p2 + y3*p3 + y4*t + y5*t2 + y6*t3 + y7*tp + y8*&
&     tp2 + y9*t2p
! Denominator of rational function approximation
    tb = z0 + z1*p + z2*p2 + z3*p3 + z4*t + z5*t2 + z6*t3 + z7*tp + z8*&
&     tp2 + z9*t2p
! Water density
    rhof_loc = ta/tb
! Derivative of numerator
    da = y1 + 2.d0*y2*p + 3.d0*y3*p2 + y7*t + 2.d0*y8*tp + y9*t2
! Derivative of denominator
    db = z1 + 2.d0*z2*p + 3.d0*z3*p2 + z7*t + 2.0*z8*tp + z9*t2
! Denominator squared
    b2 = tb*tb
! Derivative, quotient rule
    drhodp = (da*tb-ta*db)/b2
! Compressibility: (1/rhof_loc) * drhodp [1/MPa]
! Compressibility [1/Pa]
    compf_mpa_ad = compf_adv/pa_conv
    drhodp_ad = compf_mpa_ad/rhof_loc
    rhof_loc_ad = -(drhodp*compf_mpa_ad/rhof_loc**2)
    temporary_ad = drhodp_ad/b2
    da_ad = tb*temporary_ad
    ta_ad = rhof_loc_ad/tb - db*temporary_ad
    db_ad = -(ta*temporary_ad)
    b2_ad = -((da*tb-ta*db)*temporary_ad/b2)
    tb_ad = da*temporary_ad + 2*tb*b2_ad - ta*rhof_loc_ad/tb**2
    tp_ad = z8*2.0*db_ad + y8*2.d0*da_ad + z7*tb_ad + y7*ta_ad
    p3_ad = z3*tb_ad + y3*ta_ad
    t3_ad = z6*tb_ad + y6*ta_ad
    tp2_ad = z8*tb_ad + y8*ta_ad
    p2_ad = z3*3.d0*db_ad + y3*3.d0*da_ad + z2*tb_ad + y2*ta_ad + t*&
&     tp2_ad + p*p3_ad
    t2p_ad = z9*tb_ad + y9*ta_ad
    p_ad = z2*2.d0*db_ad + y2*2.d0*da_ad + z1*tb_ad + y1*ta_ad + t2*&
&     t2p_ad + t*tp_ad + p2*p3_ad + 2*p*p2_ad
    t2_ad = z9*db_ad + y9*da_ad + z5*tb_ad + y5*ta_ad + p*t2p_ad + t*&
&     t3_ad
    t_ad = z7*db_ad + y7*da_ad + z4*tb_ad + y4*ta_ad + p2*tp2_ad + p*&
&     tp_ad + t2*t3_ad + 2*t*t2_ad
    tlocal_ad = t_ad
    plocal_ad = p_ad
    temp_ad(i, j, k, ismpl) = temp_ad(i, j, k, ismpl) + tlocal_ad
    pres_ad(i, j, k, ismpl) = pres_ad(i, j, k, ismpl) + pa_conv1*&
&     plocal_ad
  END IF
END SUBROUTINE COMPF_AD

