!        Generated by TAPENADE     (INRIA, Ecuador team)
!  tapenade 3.x
!
!  Differentiation of lamf in reverse (adjoint) mode (with options noISIZE i8):
!   gradient     of useful results: *temp lamf
!   with respect to varying inputs: *temp
!   Plus diff mem management of: temp:in
! MIT License
!
! Copyright (c) 2020 SHEMAT-Suite
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!>    @brief calculate the thermal conductivity lamf in W/(m*K) of the formation water
!>    @param[in] i cell index, direction I0
!>    @param[in] j cell index, direction J0
!>    @param[in] k cell index, direction K0
!>    @param[in] ismpl local sample index
!>    @return  thermal conductivity                lamf[W/(m*K)]
!>    @details
!> calculate the thermal conductivity lamf in W/(m*K) of\n
!>formation water, given temperature in C, and salinity in mass fraction\n
!>(g/g)of NaCl. Thermal conductivity of freshwater, lamfw is calculated using\n
!>the Phillips (1981) formulation. \n
!> Phillips, S. L. "A technical databook for geothermal energy utilization."(1981).
!>Range of validity:  20 to 330°C and up to 4 molal NaCl\n
!>    input:\n
!>      pressure                            plocal [Mpa]\n
!>      temperature                         tlocal in [C]\n
SUBROUTINE LAMF_AD(i, j, k, ismpl, lamf_adv)
  use arrays

  USE ARRAYS_AD

  IMPLICIT NONE
  double precision :: lamf_adv
  INTEGER :: i, j, k, ismpl
  DOUBLE PRECISION :: tlocal, tr, tr2, tr3, tr4
  DOUBLE PRECISION :: tlocal_ad, tr_ad, tr2_ad, tr3_ad, tr4_ad
  INTEGER :: branch
  DOUBLE PRECISION :: lamf
  tlocal = temp(i, j, k, ismpl)
  IF (tlocal .LT. 0.d0) THEN
    tlocal = 0.d0
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
  IF (tlocal .GT. 300.d0) THEN
    tlocal = 300.d0
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
  tr = (tlocal+273.15d0)/273.15d0
  tr2 = tr*tr
  tr3 = tr2*tr
  tr4_ad = -(0.07344d0*lamf_adv)
  tr3_ad = 0.52577d0*lamf_adv + tr*tr4_ad
  tr2_ad = tr*tr3_ad - 1.8007d0*lamf_adv
  tr_ad = 2.8395d0*lamf_adv + tr3*tr4_ad + tr2*tr3_ad + 2*tr*tr2_ad
  tlocal_ad = tr_ad/273.15d0
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) tlocal_ad = 0.D0
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) tlocal_ad = 0.D0
  temp_ad(i, j, k, ismpl) = temp_ad(i, j, k, ismpl) + tlocal_ad
END SUBROUTINE LAMF_AD

